### ISSUE TITLE
Discord setting channel deletes config

### ISSUE THREAD

**Issue by YayoAstur** [alexemanuelol/rustPlusPlus#116]
Hi!

I've made a fresh install of the bot right now and the messages with the embeds on the settings channels disappear after a few seconds, no matter which language is set.

I've used the bot before some months ago and I don't know why its making this right now... Any clue?

Running on:
Ubuntu 20.04.5 LTS
node 16.17
git 2.25.1
latest release of the bot

**Comment by alexemanuelol** [comment]
Haven't heard of this before, were you able to resolve it?
