### ISSUE TITLE
Update Repository Commands

### ISSUE THREAD

**Issue by RoadsYT** [alexemanuelol/rustPlusPlus#119]
Hello,

I use terminal and Node.js to run the bot, I followed this [tutorial ](https://www.youtube.com/watch?v=xqcqXcWypEo&t=148s&ab_channel=AlexEmanuel), I am unsure how to update the bot, I've tried the commands listed but am still unsure.

![image](https://user-images.githubusercontent.com/122672976/212467840-50f2ba23-bfb3-423e-baee-0dc495f6d5bf.png)
This is a picture of how I start the bot, not sure if that helps for context.

Thank you!

**Comment by Squidysquid1** [comment]
> Is `npm install -g npm@9.3.0 `the correct command?

This is not the correct command you have to run the `update.bat` file if you're on windows.

The command you referenced only updates the npm command

**Comment by Richkan1** [comment]
im having trouble updating from 1.6.0 to 1.7.0
im an absolute noob regarding github etc so is there a step-to-step guide that i can follow?
starting the update.bat gives me the text in my screenshot. do i have to download 1.7.0 first and copy the files to a directory?
![grafik](https://user-images.githubusercontent.com/93288643/216225944-e102c39c-a0f7-4985-99b9-a7d042e44f8e.png)

**Comment by Richkan1** [comment]
ohh, even with a fresh install it will always install v1.6.0 after using the following command "git clone https://github.com/alexemanuelol/rustPlusPlus.git"
does that mean it doesnt link to v1.7.0?
