### ISSUE TITLE
Suggestion: Auto day / night if player is present

### ISSUE THREAD

**Issue by TheCrazyInsanity** [alexemanuelol/rustplusplus#121]
Dont turn on the light switch if nobody is online and at the base

**Comment by alexemanuelol** [comment]
So like, add an option to the AUTO-DAY/AUTO-NIGHT select menu? "AUTO-ON at HOME", or like "AUTO-ON Online"?

**Comment by alexemanuelol** [comment]
Added auto-ON and auto-OFF in 1fdf9671a5d6602a4f8287042ab91d5c5b749e26
Don't think it matter, battery capacity wise if switches are on/off. so I won't add checks if players are online or not to decide status of switches
