### ISSUE TITLE
Trackers Change - Enhancement

### ISSUE THREAD

**Issue by FBIOCE** [alexemanuelol/rustplusplus#123]
Hey,
Wanting to see if you could log when a player logs in and out through the trackers, I'd like to see how many hours each wipe they play, so if it could either tally them, or just log a log in and out event separate to the team activity though as we have multiple UI's

**Comment by alexemanuelol** [comment]
So I've added the ability to get activity notifications whenever people from trackers login/logout. But I won't add the check to see how many hours each wipe because it will be to vague.
