### ISSUE TITLE
Error: Response contain error property with value: rate_limit

### ISSUE THREAD

**Issue by undeci16** [alexemanuelol/rustplusplus#130]
Keep getting this in my terminal. https://i.imgur.com/4YMujYy.png
It's from some of my switches in discord it "qfw (V10) could not be found! Either it have been destroyed or *** have lost tool cupboard access." https://i.imgur.com/xW5Rexv.png
The switch is still there, I have TC and it doesn't lose any power. 
I can turn the switch on/off in discord and it re-finds the switch, but after some time I get the same error again. https://i.imgur.com/juaHZ9e.png

**Comment by alexemanuelol** [comment]
Could it perhaps have something to do with the amount of smart devices you currently have?

**Comment by undeci16** [comment]
I believe so, did some looking around and found that there's 25 token limit with 3 replenished each second. Different requests cost a certain amount with EntitiyInfo using 1 as I'm guessing the bot uses that to check switches. bottom of page here: https://github.com/liamcottle/rustplus.js

I'm guessing nothing can be done unless there's a way to check for the first 24 switches, wait 8 seconds for tokens to replenish then check for another 24 switches etc.

**Comment by alexemanuelol** [comment]
There is already a token replenish system in place that works in most cases, not sure if Ill dig into this any more.
