### ISSUE TITLE
Error: Cannot find module 'node:events'

### ISSUE THREAD

**Issue by Owned67** [alexemanuelol/rustPlusPlus#14]
`npm install
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@discordjs/collection@0.2.4',
npm WARN EBADENGINE   required: { node: '>=16.0.0', npm: '>=7.0.0' },
npm WARN EBADENGINE   current: { node: 'v14.16.0', npm: '8.5.0' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@discordjs/rest@0.1.1-canary.0',
npm WARN EBADENGINE   required: { node: '>=16.0.0' },
npm WARN EBADENGINE   current: { node: 'v14.16.0', npm: '8.5.0' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'discord.js@13.6.0',
npm WARN EBADENGINE   required: { node: '>=16.6.0', npm: '>=7.0.0' },
npm WARN EBADENGINE   current: { node: 'v14.16.0', npm: '8.5.0' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@discordjs/builders@0.11.0',
npm WARN EBADENGINE   required: { node: '>=16.0.0', npm: '>=7.0.0' },
npm WARN EBADENGINE   current: { node: 'v14.16.0', npm: '8.5.0' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@discordjs/collection@0.4.0',
npm WARN EBADENGINE   required: { node: '>=16.0.0', npm: '>=7.0.0' },
npm WARN EBADENGINE   current: { node: 'v14.16.0', npm: '8.5.0' }
npm WARN EBADENGINE }

up to date, audited 210 packages in 2s

12 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
`

`F:\rust\rustPlusPlus>node index.js
internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module 'node:events'
Require stack:
- F:\rust\rustPlusPlus\node_modules\discord.js\src\client\BaseClient.js
- F:\rust\rustPlusPlus\node_modules\discord.js\src\index.js
- F:\rust\rustPlusPlus\index.js
←[90m    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)←[39m
←[90m    at Function.Module._load (internal/modules/cjs/loader.js:725:27)←[39m
←[90m    at Module.require (internal/modules/cjs/loader.js:952:19)←[39m
←[90m    at require (internal/modules/cjs/helpers.js:88:18)←[39m
    at Object.<anonymous> (F:\rust\rustPlusPlus\node_modules\←[4mdiscord.js←[24m\src\client\BaseClient.js:3:22)
←[90m    at Module._compile (internal/modules/cjs/loader.js:1063:30)←[39m
←[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)←[39m
←[90m    at Module.load (internal/modules/cjs/loader.js:928:32)←[39m
←[90m    at Function.Module._load (internal/modules/cjs/loader.js:769:14)←[39m
←[90m    at Module.require (internal/modules/cjs/loader.js:952:19)←[39m {
  code: ←[32m'MODULE_NOT_FOUND'←[39m,
  requireStack: [
    ←[32m'F:\\rust\\rustPlusPlus\\node_modules\\discord.js\\src\\client\\BaseClient.js'←[39m,
    ←[32m'F:\\rust\\rustPlusPlus\\node_modules\\discord.js\\src\\index.js'←[39m,
    ←[32m'F:\\rust\\rustPlusPlus\\index.js'←[39m
  ]
}`

edit: updating nodejs in progress..

**Comment by Owned67** [comment]
so okay, sometinh wrong:
```
node index.js
2022-2-11 18:05:09 INFO: LOGGED IN AS: RustPlus#3143
2022-2-11 18:05:09 INFO: Waiting 5 seconds to make sure all text channels are created
2022-2-11 18:05:10 ERROR: {"rawError":{"message":"Missing Access","code":50001},"code":50001,"status":403,"method":"put","url":"https://discord.com/api/v9/applications/XXXXXXXXXXXXXXXXXX/guilds/268XXXXXXXXXXXXXXX/commands"}
```

RustPlusPlus channel is created with a lot settings... so idk what is wrong with this message above

**Comment by alexemanuelol** [comment]
By the looks of it you didn't create the bot invitation with the correct options. Check the README in the section 'Create a discord bot'.

> Click on OAuth2 tab on the website.
> Scroll down to OAuth2 URL Generator.
> Check the following boxes: bot and applications.commands
> Scroll down to Bot permissions and select the following: Administrator
> Copy the URL (This is used to invite you discord bot to discord servers (guilds))

**Comment by Owned67** [comment]
Bot have administrator privileges, i can't make better and ive follow the readme

**Comment by alexemanuelol** [comment]
Have you selected **bot** and **applications.commands**?

**Comment by alexemanuelol** [comment]
Because I think it's the applications.commands that might be missing

**Comment by Owned67** [comment]
> Have you selected **bot** and **applications.commands**?

ye
![rustplus](https://user-images.githubusercontent.com/1497809/153659689-2a655fba-8150-4975-a415-9a35c71fbdbe.gif)
s

**Comment by alexemanuelol** [comment]
Is it possible that its the same bot you used for the other bot? Try to Create a completely new discord bot.

**Comment by Owned67** [comment]
no it's a new bot

**Comment by alexemanuelol** [comment]
What nodejs version are you running?

**Comment by alexemanuelol** [comment]
https://flutterq.com/solved-discordapierror50001-missing-access/
Test solution 2

**Comment by alexemanuelol** [comment]
Oh nevermind, that was for another problem. Your problem is solution 1...

**Comment by Owned67** [comment]
> What nodejs version are you running?

v16.14.0

**Comment by Owned67** [comment]
i can't make better sorry, ive follow your readme...

**Comment by alexemanuelol** [comment]
https://stackoverflow.com/questions/68886388/trying-to-register-commands-discordapierror50001-missing-access

Same problem, same solution...

**Comment by Owned67** [comment]
> https://stackoverflow.com/questions/68886388/trying-to-register-commands-discordapierror50001-missing-access
> 
> Same problem, same solution...

Ive re created and same.. have you see my gif??? i can't make better guy...

**Comment by alexemanuelol** [comment]
Or did you just click the copy button?

**Comment by Owned67** [comment]
> Ive re created and same.

Ive re created and same.

**Comment by alexemanuelol** [comment]
Did you remove it from your server and re-invite:ed?

**Comment by Owned67** [comment]
It's again a new bot and other was kicked and all channel removed

**Comment by alexemanuelol** [comment]
https://discordjs.guide/preparations/adding-your-bot-to-servers.html#creating-and-using-your-invite-link

Hit me up on Discord instead: Alexemanuelol#8259

**Comment by Owned67** [comment]
I know how to invite a bot thanks ^^ Im off for tonight, tomorrow im up ;)

**Comment by alexemanuelol** [comment]
Okioki, then Im afraid I can't really help you 😕

**Comment by Owned67** [comment]
that weird really, im checking in files, open 268426701401227264.json and found:
 ```
 "channelId": {
    "category": "941782038401409034",
    "information": "941782039412215828",
    "servers": "941782040146219039",
    "settings": "941782040846671874",
    "events": "941782042318876763"
  },
``` all is created so why it give this error? :x

**Comment by alexemanuelol** [comment]
It's when it's trying to register the Slash Commands for your guild. And usually it is solved by adding the 'applications.commands' to the invitation URL.

**Comment by Owned67** [comment]
wtf, ive re launch for the X times and no error :D xD Solved so
