### ISSUE TITLE
In-game commands do not work

### ISSUE THREAD

**Issue by tddustinnguyen** [alexemanuelol/rustPlusPlus#144]
in-game command prefix is set to .
in-game commands are enabled

Seeing if there's any methods to troubleshoot. Nothing on console when typing in in-game commands.

**Comment by alexemanuelol** [comment]
What server is it?

**Comment by tddustinnguyen** [comment]
Icefuse 2x warden

**Comment by tddustinnguyen** [comment]
https://www.battlemetrics.com/servers/rust/3410403

**Comment by alexemanuelol** [comment]
I think this is because the server uses some sort of clan plugin which messed up teamchat somehow. You can still run commands through discord commands channel.
