### ISSUE TITLE
Bot disconnecting from server on server restart.

### ISSUE THREAD

**Issue by C74K** [alexemanuelol/rustplusplus#145]
Bot disconnecting from server on server restart.
And returning errors.

**Comment by C74K** [comment]
![image](https://user-images.githubusercontent.com/3368595/227991888-930f0f70-28e2-4baa-9ab3-fa056597e471.png)

**Comment by C74K** [comment]
not fixed - bot lose connection to server after game server restart

**Comment by alexemanuelol** [comment]
I've created a branch reconnect_issue where you can test to see if it still happens @C74K

**Comment by alexemanuelol** [comment]
Fixed in: d2e672ddd1f793b2f0f04822f137f44c6be0f46a
