### ISSUE TITLE
/help doesnt do anything?

### ISSUE THREAD

**Issue by Nou4r** [alexemanuelol/rustPlusPlus#15]
Been trying to connect a switch but there is no docoumentation and /help doesnt work.
![image](https://user-images.githubusercontent.com/12816677/153843730-439f9503-29f4-405b-be21-6514d1679452.png)

**Comment by alexemanuelol** [comment]
I know I know, I haven't even made a proper release yet of it, it's still much under development and things are likely to change at this stage. Smart Switches is not implemented yet, Im currently working on it tho so a first draft will probably be available today or tomorrow. But have no documentation yet.
