### ISSUE TITLE
Docker Image Entry Point Issues

### ISSUE THREAD

**Issue by joshualawson** [alexemanuelol/rustplusplus#160]
Seems to be an issues with the docker image entry point

When using docker-compose to spin up the rustPlusPlus bot I get the following error:

```
Attaching to rpp
rpp    | exec /usr/local/bin/docker-entrypoint.sh: exec format error
rpp exited with code 1
```

Weirdly I can't seem to fin the entry point in any of the code within this repo

**Comment by joshualawson** [comment]
due to the image not being built for ARM64 (RaspPI) had to build the image myself, closing)

**Comment by alexemanuelol** [comment]
Feel free to leave a PR for ARM64 compatible image.
