### ISSUE TITLE
Add step trace in /map image for Patrol Helicopter, Cargoship

### ISSUE THREAD

**Issue by alexemanuelol** [alexemanuelol/rustplusplus#162]
Maybe for Chinook 47 too?

**Comment by FaiThiX** [comment]
by step trace you mean a line of each path the patrol helicopter fly?

**Comment by alexemanuelol** [comment]
Correct, Im already working on this atm

**Comment by alexemanuelol** [comment]
I was thinking it would be part of map all command

**Comment by alexemanuelol** [comment]
Added in 070d97c2ab65aa0f08c1c40afbb0735accc7d424
GraphicsMagick is required to get it to work.
Can be downloaded here: http://www.graphicsmagick.org/download.html

**Comment by Beaueyjangles** [comment]
Would it be possible to timeline teams movements with player deaths marked. Different coloured lines for teams members. Able to see team mates movements over different dates of the wipe would be amazing bonus feature to /map all aswell.
