### ISSUE TITLE
update- error on startup 

### ISSUE THREAD

**Issue by undeci16** [alexemanuelol/rustplusplus#166]
`2023-4-02 11:20:30 ERROR: Message edit failed: ,Error: ENOENT: no such file or directory, stat 'C:\Users\bran_\Desktop\rustplus3\rustPlusPlus\src\resources\images\electrics\undefined'

2023-4-02 11:20:30 Unhandled Rejection: ,TypeError: Cannot read properties of undefined (reading 'id'): undefined

TypeError: Cannot read properties of undefined (reading 'id') 

at Object.sendSmartSwitchGroupMessage 
(C:\Users\bran_\Desktop\rustplus3\rustPlusPlus\src\discordTools\discordMessages.js:183:85)

at async module.exports (C:\Users\bran_\Desktop\rustplus3\rustPlusPlus\src\discordTools\SetupSwitchGroups.js:33:9)

at async Object.execute (C:\Users\bran_\Desktop\rustplus3\rustPlusPlus\src\rustplusEvents\connected.js:81:9)`

**Comment by alexemanuelol** [comment]
Could be solved by just re-creating your smart switch group.
