### ISSUE TITLE
Add "+minute offset" for auto-day/night switches

### ISSUE THREAD

**Issue by simpyhub** [alexemanuelol/rustplusplus#168]
Would be nice to have the option to set a extra minute offset for enabling/disabling switches with auto-day/night setting.

Example; I use auto-night option for my switch that has all lights in base, but I want the lights to turn on 2 minutes before nighttime actually happens, because its quite dark already when nighttime happens.

Another use case is having auto-night setting for heaters in a hemp base. Usually its already cold when nighttime happens, so I would like to enable the switch 2 minutes before nighttime and have it running for 2 minutes extra after daytime happens.

**Comment by alexemanuelol** [comment]
This would involve changing the values of sunrise and sunset which is used to base the time (time till night/ time till day). Ofcourse it would be possible to do some sort of bypass but that would involve a bit of work and I dont feel like its worth the effort unfortunately 😅
