### ISSUE TITLE
Switch groups no longer respond to ingame commands 1.10

### ISSUE THREAD

**Issue by YakovAU** [alexemanuelol/rustplusplus#172]
use this alot in our villages. since updating to 1.10 the bot isnt recognizing switch group ingame commands.
thanks

**Comment by YakovAU** [comment]
nevermind it works, i think before it would show the status or toggle if you just did !turrets for example instead of !turrets on or off

**Comment by alexemanuelol** [comment]
c6bf50ff5f4f997f814ae0f830b9481a71332f79
