### ISSUE TITLE
Connect to Rust server

### ISSUE THREAD

**Issue by KimViktor522** [alexemanuelol/rustPlusPlus#18]
I don't know how to connect Rustplusplus bot to my rust server. Unfortunately, I couldn't find this information in the "Readme".

**Comment by seanecoffey** [comment]
The same way you connect it to your phone app.
Send/resend the notification in Rust when you're connected to the server, then in discord under the bot channel "servers", click "connect" on the message that should be sent.

**Comment by KimViktor522** [comment]
Many thanks! For some unknown reason, Steam did not connect to me (it connected on the 4th attempt).
Can you please add in the "Readme" that the command (/credential set) will appear on the command line with all the data. For a long time I could not figure out where I should get all this data for (/credential set).

P.S. Thanks for doing such cool stuff for Rust!!!

**Comment by KimViktor522** [comment]
And there is also a suggestion to add a bat file for faster launch in two clicks.
Change from "Start.txt" to "Start.bat".
[Start.txt](https://github.com/alexemanuelol/rustPlusPlus/files/8350556/Start.txt)
