### ISSUE TITLE
ERROR: {"code":"DisallowedIntents"} I need to fix this, does anyone know how?

### ISSUE THREAD

**Issue by xdrajfxd** [alexemanuelol/rustplusplus#180]
![image](https://user-images.githubusercontent.com/130723913/231930560-a6f0089d-ab83-4e9e-bf31-93cf1e539f2f.png)

**Comment by C74K** [comment]
manual !

**Comment by alexemanuelol** [comment]
Check the documentation
https://github.com/alexemanuelol/rustplusplus/blob/master/docs/discord_bot_setup.md

**Comment by C74K** [comment]
> Check the documentation https://github.com/alexemanuelol/rustplusplus/blob/master/docs/discord_bot_setup.md

can make you old video private becose peoples dont read  whats is writen under video,
