### ISSUE TITLE
[BUG] Team member information steamid not working

### ISSUE THREAD

**Issue by Pokeylooted** [alexemanuelol/rustplusplus#181]
There's this random bug with Team member information showing links instead of name:
![image](https://user-images.githubusercontent.com/79169880/232258315-dbeff547-5327-4dfd-be0a-8c6c4c57c8b9.png)

**Comment by alexemanuelol** [comment]
If you remember, what were their in-game name?

**Comment by alexemanuelol** [comment]
This seem to happen when player name is empty.
I've made a fix for it in: 51a54f05abb7fde35d68e283390c51bbbc607228
