### ISSUE TITLE
Add !uptime command to show how long bot has been connected to a rust server

### ISSUE THREAD

**Issue by alexemanuelol** [alexemanuelol/rustplusplus#183]
- Create !uptime command to see how long the bot has been connected to a rust server
- Create a slash command to see how long the bot has been on (?)

**Comment by selvalogesh** [comment]
Hey, I wanted to contribute but I don't have the Rust game. Just made a commit, would appreciate if someone could help test it. Thanks !

**Comment by selvalogesh** [comment]
Hi, any updates on this issue ? Would appreciate if someone could checkout and test out the commit. Thank you 😊 !

**Comment by alexemanuelol** [comment]
Added in: 1579cde771737a6349ff8da4651f892e48968618
