### ISSUE TITLE
You can please add commands (!day) and (!night)

### ISSUE THREAD

**Issue by KimViktor522** [alexemanuelol/rustPlusPlus#19]
Good afternoon! Please add these two commands (!day) and (!night). 
(!day) - time until the end of the day (remaining time until ~00:00). 
(!night) - time until the end of the night (remaining time until ~07:00).
Thanks in advance.

**Comment by alexemanuelol** [comment]
This functionality already exist in the timr command. You just have to let the bot run on the server for 24 in-game hours
