### ISSUE TITLE
When internet is down bot is crashing

### ISSUE THREAD

**Issue by Rastlinek** [alexemanuelol/rustplusplus#195]
Hi!
After a break in the internet connection (Wi-Fi), the program freezes and stops working. It needs to be closed and restarted. No matter break in internet was 10s, is crashing.
![Przechwytywanie](https://github.com/alexemanuelol/rustplusplus/assets/28508380/0131b8ce-37c5-47ec-9103-a560bdb063c7)

**Comment by alexemanuelol** [comment]
I didn't experience any crash, I did however have to reconnect to the server (Click disconnect in servers channel and then connect again)

**Comment by alexemanuelol** [comment]
Will be solved with reconnect_issue branch
