### ISSUE TITLE
Add step in documentation to start the bot

### ISSUE THREAD

**Issue by Richkan1** [alexemanuelol/rustPlusPlus#196]
The last step 16 in the Discord setup documentation (https://github.com/alexemanuelol/rustplusplus/blob/master/docs/discord_bot_setup.md) is that the bot should show up on the Discord server.
The guide continues with how to setup FCM Credentials which wont be successful if you blindly follow the guide.

Add step 17 to start the bot with "npm start run"
![image](https://github.com/alexemanuelol/rustplusplus/assets/93288643/342df0d1-cba0-4f7a-b12f-6f856b4dc49d)

**Comment by alexemanuelol** [comment]
Fixed in: 6f51c121ea84ee6d9c8442297845358171308a32
