### ISSUE TITLE
stuck reconnecting to server, parse error

### ISSUE THREAD

**Issue by majokko** [alexemanuelol/rustplusplus#199]
using docker but tried node as well
i can't seem to connect to a server, having parse error and reconnecting to server spam in logs as well as on discord.
![Screenshot_20230708_045616](https://github.com/alexemanuelol/rustplusplus/assets/101653707/3be3acd9-ac3b-4e38-9aa0-b6376b56fd89)
![Screenshot_20230708_045702](https://github.com/alexemanuelol/rustplusplus/assets/101653707/75cae5db-cfd8-466e-8be1-eb0670e18d16)
any idea why?

**Comment by alexemanuelol** [comment]
What version of the repository are you running? Like what git hash

**Comment by majokko** [comment]
43816998287840860e8e493ff16683bc44ec88f3 
its from a fresh reinstall of master

**Comment by alexemanuelol** [comment]
Should be solved in latest
