### ISSUE TITLE
Can not add credentials.

### ISSUE THREAD

**Issue by kalakoa** [alexemanuelol/rustplusplus#203]
User without admin permissions in discord can't add credentials to bot.
Getting error: WARNING: You don't have permission to do this.
Adding his role via /role do not helps.

Me as discord server admin can add credentials without any problems.

**Comment by PandeoF1** [comment]
Try using "needAdminPrivileges" in config/index.js ;)

**Comment by alexemanuelol** [comment]
Works fine for me.
