### ISSUE TITLE
How can I use step-trace with graphicsmagick?

### ISSUE THREAD

**Issue by DannielStevan** [alexemanuelol/rustplusplus#209]
I was seeing recently in the [documentation ](https://github.com/alexemanuelol/rustplusplus/blob/master/docs/installation.md)that it was possible to use [graphicsmagick](http://www.graphicsmagick.org/download.html) to see the step-trace of the cargoship and the patrol. My question is how can I use it? Is there any instruction or documentation for me to do it? thank you very much in advance.

**Comment by alexemanuelol** [comment]
`/map all` Should give you step-trace if you have graphicsmagick installed where the bot is hosted.

**Comment by C74K** [comment]
not working
 2023-7-30 04:55:35 ERROR: Error: Command failed: gm convert: No decode delegate for this image format (/root/A/src/resources/images/maps/146878770672828416_map_full.png).

2023-7-30 04:55:35 ERROR: There was an error while executing this command!
