### ISSUE TITLE
questions

### ISSUE THREAD

**Issue by aziz191546** [alexemanuelol/rustPlusPlus#21]
how use this command /credentials set ? whats ​keys_private_key,​keys_auth_secret,etc...
and i can use bot in multiple rust servers and discord servers ?

**Comment by alexemanuelol** [comment]
> how use this command /credentials set ? whats ​keys_private_key,​keys_auth_secret,etc...
> and i can use bot in multiple rust servers and discord servers ?

Read credentials section in the readme file.

You can use the bot on multiple discord servers but only one rust server can be connected simultaneously.

**Comment by alexemanuelol** [comment]
Bot owner needs to give a invitation url to the users

**Comment by aziz191546** [comment]
i mean how simple users can use bot in discord because only bot owner can connect bot with rust server
