### ISSUE TITLE
map all dont work

### ISSUE THREAD

**Issue by C74K** [alexemanuelol/rustplusplus#211]
2023-7-30 04:55:35 ERROR: Error: Command failed: gm convert: No decode delegate for this image format (/root/A/src/resources/images/maps/146878770672828416_map_full.png).

2023-7-30 04:55:35 ERROR: There was an error while executing this command!

**Comment by C74K** [comment]
dont working on 1.12

**Comment by alexemanuelol** [comment]
Should work on latest

**Comment by C74K** [comment]
checking map generated with player location and nothing more.
