### ISSUE TITLE
Extend battlemetrics tracking to track all players

### ISSUE THREAD

**Issue by alexemanuelol** [alexemanuelol/rustplusplus#229]
Create a Battlemetrics Structure:
- Client should have an object that stores all Battlemetrics instances with the battlemetricsId as the key.
- During startup, all Battlemetrics instances will be setup and trackers will be read from instance file into each Battlemetrics instance.
- Battlemetrics instance read/write to instance file for trackers.
- Move steam scrape calls to Battlemetrics structure.
- Move battlemetrics handling into the structure.
- Move all api calls into the structure.
- When changing battlemetricsId of a tracker, move tracker from one battlemetrics instance to another.

Potential features:
- Track all people on the server.
- Easily add new/remove players to trackers (instant update).
- Get offline time of all players.
- Analyze player online patterns (Based on names).
- Continuously update people going online/offline.
- Have an embed that display all online players.
- Settings for what features to be enabled etc...

**Comment by PandeoF1** [comment]
You wan't to track all the players of a servers ???

**Comment by alexemanuelol** [comment]
Or at least use the data. Currently I have the data in the variable "onlinePlayers", but I dont use it

**Comment by kunihir0** [comment]
do you mean like a player list then we can attach a button to that to track player ?

**Comment by alexemanuelol** [comment]
> do you mean like a player list then we can attach a button to that to track player ?  then paginate the results

Trackers rely on steamid which is not provided on the battlemetrics page, so no.

**Comment by alexemanuelol** [comment]
Add battlemetrics structure. Also keep track of player online activity, what hours a certain player usually is online etc

**Comment by alexemanuelol** [comment]
Partially completed in: 6ab07a4aa9032a4e528e06c3e024bdb444e44e3e

Left is:
- Analyze player online patterns (Based on names).
- Have an embed that display all online players.
- Settings for what features to be enabled etc...

**Comment by alexemanuelol** [comment]
Create a setting for several tracker stuff to notify:
- name changes
- server players (connect/disconnect for all players on the server)
- server name change?
- max players change?
- server rank?
- etc

**Comment by alexemanuelol** [comment]
Considered finished in: 64505b4e25e6df56896c6f3e6d33812908d01f21
