### ISSUE TITLE
The shops

### ISSUE THREAD

**Issue by KimViktor522** [alexemanuelol/rustPlusPlus#23]
First, could you please add an alert for new open stores instead of open empty stores?
Secondly, is there a team to search for items for sale? (for example, I want to know if anyone sells workbench 3, if so, for what)

**Comment by alexemanuelol** [comment]
Unfortunately I determine vending machines by their x/y location, everytime a vending machine opens, it's ID changes which makes it unreliable. It would be possible to make it notify whenever a shop is opened, but that could mean alot of notifications can appear when people turn their vending machinew on and off alot. I am planning on adding market functionality, but haven't done it yet.

**Comment by KimViktor522** [comment]
The bot does not report to the team chat about the appearance of the patrol helicopter on the map, although the notification in the discord comes.
![image](https://user-images.githubusercontent.com/61150502/162614710-2dd7f016-56d9-4022-9c05-938efac8c469.png)
![image](https://user-images.githubusercontent.com/61150502/162614740-cc100cfd-e589-4f71-aafc-668eb6e1c847.png)
![image](https://user-images.githubusercontent.com/61150502/162614851-eabab7f0-6afc-4b02-9566-323f1f86a688.png)

**Comment by alexemanuelol** [comment]
This has nothing to do with your first issue. Try to run /reset discord
