### ISSUE TITLE
add craft command

### ISSUE THREAD

**Issue by alexemanuelol** [alexemanuelol/rustplusplus#234]
/craft [item] [quantity]

Scrape:
https://rustlabs.com/item/workbench-level-3#tab=workbench
And find items that do not require workbench to be crafted

**Comment by FaiThiX** [comment]
a list with all items can be found here: https://rustlabs.com/group=itemlist

**Comment by alexemanuelol** [comment]
Added in: 0fe9c8021f8baa3435d9983163d5dc5530d593d8
