### ISSUE TITLE
[Suggestion] More Options for Trademark

### ISSUE THREAD

**Issue by SSyl** [alexemanuelol/rustPlusPlus#24]
I actually like the idea of the trademark/bit prefix before messages, but I find "rustPlusPlus | " before every message a little too cumbersome.

Would it be possible to add additional options such as:

[Rust++], RPP, etc.

In addition maybe add the option to choose wether it's separated by a pipe, brackets, or a semi colon or something like that?

**Comment by alexemanuelol** [comment]
Added a select menu with three options, rustPlusPlus, Rust++ or empty.
See commit 547853d7df21cf7e89b60f94acba66f9a64c0d42
