### ISSUE TITLE
Add Discord role based permissions

### ISSUE THREAD

**Issue by justinj0001** [alexemanuelol/rustplusplus#241]
Currently the Discord permissions are reset every time the bot/host is restarted.  This defaults to everyone having access to all channels.  If one changes the category permissions, #commands and #teamchat are set to not sync.
This is problematic when the Discord server has a public channel as they can then see anything posted in team chat as well as interact with switches, alarms etc.
This could be remedied by defaulting the category (and having all channels synced) to admin only and then have settings for all/individual channels to set only specific role(s) to have permissions when the server is restarted.

**Comment by alexemanuelol** [comment]
https://github.com/alexemanuelol/rustplusplus/blob/master/docs/commands.md#role
