### ISSUE TITLE
Improvement idea

### ISSUE THREAD

**Issue by R23A** [alexemanuelol/rustplusplus#246]
A feature to detect locked crates in the same way it currently does for cargo, attack helicopter, and Chinook spawns. This feature would notify Discord and use text-to-speech (TTS) when small and large oil rig re-spawns happen and when and/or where the Chinook drops a locked crate. thanks

**Comment by FaiThiX** [comment]
sadly fp removed that information from rust+ a few months ago. Thats why we can't get this information anymore.

**Comment by R23A** [comment]
Oooh that is sad, since we have the in game notification I thought it was possible, but okay, thanks for the response
