### ISSUE TITLE
The storage monitor does not correctly display the type where it is installed

### ISSUE THREAD

**Issue by PR0TX** [alexemanuelol/rustplusplus#251]
For some reason, it does not show that the monitor is connected to the cabinet, but it shows that it is connected to the drawer.
I play on the Facepunch Large 1 server
![Screenshot 2023-10-10 144845](https://github.com/alexemanuelol/rustplusplus/assets/58433688/38433a3f-7eeb-4034-8216-024f56409743)
![Screenshot 2023-10-10 144622](https://github.com/alexemanuelol/rustplusplus/assets/58433688/9e39002c-0dd6-48d7-a672-206bb22d45c5)
![Screenshot 2023-10-10 144542](https://github.com/alexemanuelol/rustplusplus/assets/58433688/0463bf6e-8500-4b79-abc5-bb1596645b15)

**Comment by alexemanuelol** [comment]
Might be that when you paired, the storage monitor had no power

**Comment by PR0TX** [comment]
Thanks for the quick reply

The same result if removed and connected again (with a constantly connected power supply from a small battery to which 1 solar panel is connected). I tried rebooting the bot, resetting the settings, deleting the server, and changing the language to English.

**Comment by alexemanuelol** [comment]
Oh wait... didnt facepunch do some change with the tool cupboard this force wipe?

**Comment by alexemanuelol** [comment]
Ahh yea one more tool slot 😂 That's why its not working, it checks how many slots there is to see if it is a tc or box. Ill fix it later👌

**Comment by alexemanuelol** [comment]
Solved in: 63eb688305136f882926e6c3c14ba40886d173da
