### ISSUE TITLE
Any way to stop channel permissions resetting on restart?

### ISSUE THREAD

**Issue by Sc0ttChegg** [alexemanuelol/rustplusplus#256]
I've seen similar posted but not sure how they are solved.

Bot runs great and populates channels.
Run /role to set group visibility, works fine, or leave on everyone works too.
Set sub channel permissions on "settings" and "server" channels to block view, works.
Restart server/bot and they have all permissions restored.

Is there a way to stop this happening as I dont want these 2 channels visible but want access as admin.
Hope that makes sense.

**Comment by alexemanuelol** [comment]
As of now, no way to stop that happening. permissions are reinforced at startup

**Comment by Sc0ttChegg** [comment]
Hey alexemanuelol, "As of now" Possible it will change? Still an awesome Bot either way, appreciate your work!

Either way thanks for the reply, at least I know it's not somehing I'm overlooking.

**Comment by alexemanuelol** [comment]
Probably not hehe :)
