### ISSUE TITLE
[ERROR] Message send failed: DiscordAPIError[50035]: Invalid Form Body

### ISSUE THREAD

**Issue by Fruschel** [alexemanuelol/rustplusplus#257]
Hey :)

I get following error as I try to connect a Rust server with RustPlusPlus.. :/

I don't get anything written in the channel #servers where I could connect RustPlusPlus and this error got thrown in console:
![image](https://github.com/alexemanuelol/rustplusplus/assets/20825400/54a050c4-7a80-40f3-a426-d1361a5f901c)

Anybody got a clue what this could be it :O

**Comment by alexemanuelol** [comment]
#255 already covers it

**Comment by alexemanuelol** [comment]
Thanks for reporting any way :)

**Comment by alexemanuelol** [comment]
Seems all Rustafied servers were having trouble with it

**Comment by alexemanuelol** [comment]
Im about to test it now :)

**Comment by alexemanuelol** [comment]
Solved in: afbdc686c1422d4e359cbc58de57c16302b9d021
