### ISSUE TITLE
Bot Crashing Due To Bad URL In Thumbnail

### ISSUE THREAD

**Issue by Akandesh** [alexemanuelol/rustplusplus#259]
Ran into this error `ERROR: Message send failed: ,DiscordAPIError[50035]: Invalid Form Body embeds[0].thumbnail.url[URL_TYPE_INVALID_URL]: Not a well formed URL` and after a lot of debugging I found it's because the thumbnail URL contained spaces (https://cdn.rustafied.systems/server-header-images/EU Long 3.png). 

The fix is to simply replace all spaces with the URL encoded variant %20. 
In this case replace ```thumbnail: `${server.img}`,``` with ```thumbnail: `${server.img.replaceAll(' ', '%20')}`,``` [HERE](https://github.com/alexemanuelol/rustplusplus/blob/master/src/discordTools/discordEmbeds.js#L96C31)
This needs to be done in every place where `server.img` is used, not just here.

Sorry for not sending a pull request instead but I've modified a lot of other things too and too lazy to figure that out.

**Comment by alexemanuelol** [comment]
Have you tried latest master?
