### ISSUE TITLE
/role set - bug

### ISSUE THREAD

**Issue by C74K** [alexemanuelol/rustplusplus#263]
use /role dont give acess to read category history.

**Comment by alexemanuelol** [comment]
Works fine for me, so explain what is happening for you.

**Comment by C74K** [comment]
![Screenshot_1](https://github.com/alexemanuelol/rustplusplus/assets/3368595/f13f2cbe-8a6f-47da-822f-c4105473b566)

**Comment by alexemanuelol** [comment]
Explain what you are doing to reproduce it

**Comment by C74K** [comment]
i join to server from test account and add role to user nothing more,

**Comment by C74K** [comment]
not completed

**Comment by Richkan1** [comment]
if you cant see the message history you have set the permissions for your discord role wrong.
/role command is solely for hiding/make rust++ channels visible.
