### ISSUE TITLE
[ERROR] Error connecting smart switches

### ISSUE THREAD

**Issue by PR0TX** [alexemanuelol/rustplusplus#264]
For some reason, when trying to connect smart switches, the following error occurs. After it, the commands still work, but after restarting the bot, all commands stop working precisely because of the game. I noticed even after the update that a new option to automatically enable / disable smart switches was added.
I play on the Facepunch Large 1 server
![Screenshot 2023-11-05 043913](https://github.com/alexemanuelol/rustplusplus/assets/58433688/b6a7c480-95f3-4e2f-a62a-8cec920ceb32)

**Comment by alexemanuelol** [comment]
Looks like there is a restricting on how many characters that can be displayed on select menu descriptions. The russian translation is too long, Ill add this limitation in crowdin.

**Comment by alexemanuelol** [comment]
Solved in: 7e557f434d02770ffe5292a25273d316c208a76c
