### ISSUE TITLE
Map image not getting updated after wipe

### ISSUE THREAD

**Issue by Didstriker** [alexemanuelol/rustPlusPlus#27]
I was using the bot on a wipe, and after It wiped yesterday, the map image on the #information Channel is still displaying last wipe map

**Comment by alexemanuelol** [comment]
Yea the continuous update of the map im the information channel is very buggy, dont think discord likes updating an image of that size continuously. So Ill remove it and add a command instead

**Comment by alexemanuelol** [comment]
Fixed in commit a5d7809523774fbc52d199fce7550f68d5aca60b
