### ISSUE TITLE
Why can't my NPM start run run run the robot

### ISSUE THREAD

**Issue by Sxyamr** [alexemanuelol/rustplusplus#285]
**The first time I run it, it shows these, how should I solve them**

> rustplusplus@1.15.0 start
> ts-node . run

/root/rustplusplus/node_modules/.store/ts-node@10.9.2/node_modules/ts-node/src/index.ts:859
    return new TSError(diagnosticText, diagnosticCodes, diagnostics);
           ^
TSError: ⨯ Unable to compile TypeScript:
index.ts:21:17 - error TS2580: Cannot find name 'require'. Do you need to install type definitions for node? Try `npm i --save-dev @types/node`.

21 const Discord = require('discord.js');
                   ~~~~~~~
index.ts:22:12 - error TS2580: Cannot find name 'require'. Do you need to install type definitions for node? Try `npm i --save-dev @types/node`.

22 const Fs = require('fs');
              ~~~~~~~
index.ts:23:14 - error TS2580: Cannot find name 'require'. Do you need to install type definitions for node? Try `npm i --save-dev @types/node`.

23 const Path = require('path');
                ~~~~~~~
index.ts:25:20 - error TS2580: Cannot find name 'require'. Do you need to install type definitions for node? Try `npm i --save-dev @types/node`.

25 const DiscordBot = require('./src/structures/DiscordBot');
                      ~~~~~~~
index.ts:44:34 - error TS2304: Cannot find name '__dirname'.

44     if (!Fs.existsSync(Path.join(__dirname, 'logs'))) {
                                    ~~~~~~~~~
index.ts:45:32 - error TS2304: Cannot find name '__dirname'.

45         Fs.mkdirSync(Path.join(__dirname, 'logs'));
                                  ~~~~~~~~~
index.ts:48:34 - error TS2304: Cannot find name '__dirname'.

48     if (!Fs.existsSync(Path.join(__dirname, 'instances'))) {
                                    ~~~~~~~~~
index.ts:49:32 - error TS2304: Cannot find name '__dirname'.

49         Fs.mkdirSync(Path.join(__dirname, 'instances'));
                                  ~~~~~~~~~
index.ts:52:34 - error TS2304: Cannot find name '__dirname'.

52     if (!Fs.existsSync(Path.join(__dirname, 'credentials'))) {
                                    ~~~~~~~~~
index.ts:53:32 - error TS2304: Cannot find name '__dirname'.

53         Fs.mkdirSync(Path.join(__dirname, 'credentials'));
                                  ~~~~~~~~~
index.ts:56:34 - error TS2304: Cannot find name '__dirname'.

56     if (!Fs.existsSync(Path.join(__dirname, 'maps'))) {
                                    ~~~~~~~~~
index.ts:57:32 - error TS2304: Cannot find name '__dirname'.

57         Fs.mkdirSync(Path.join(__dirname, 'maps'));
                                  ~~~~~~~~~
index.ts:61:1 - error TS2580: Cannot find name 'process'. Do you need to install type definitions for node? Try `npm i --save-dev @types/node`.

61 process.on('unhandledRejection', error => {
   ~~~~~~~
index.ts:61:34 - error TS7006: Parameter 'error' implicitly has an 'any' type.

61 process.on('unhandledRejection', error => {
                                    ~~~~~
index.ts:68:1 - error TS2304: Cannot find name 'exports'.

68 exports.client = client;
   ~~~~~~~

    at createTSError (/root/rustplusplus/node_modules/.store/ts-node@10.9.2/node_modules/ts-node/src/index.ts:859:12)
    at reportTSError (/root/rustplusplus/node_modules/.store/ts-node@10.9.2/node_modules/ts-node/src/index.ts:863:19)
    at getOutput (/root/rustplusplus/node_modules/.store/ts-node@10.9.2/node_modules/ts-node/src/index.ts:1077:36)
    at Object.compile (/root/rustplusplus/node_modules/.store/ts-node@10.9.2/node_modules/ts-node/src/index.ts:1433:41)
    at Module.m._compile (/root/rustplusplus/node_modules/.store/ts-node@10.9.2/node_modules/ts-node/src/index.ts:1617:30)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Object.require.extensions.<computed> [as .ts] (/root/rustplusplus/node_modules/.store/ts-node@10.9.2/node_modules/ts-node/src/index.ts:1621:12)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Function.Module._load (node:internal/modules/cjs/loader:960:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12) {
  diagnosticCodes: [
    2580, 2580, 2580, 2580,
    2304, 2304, 2304, 2304,
    2304, 2304, 2304, 2304,
    2580, 7006, 2304
  ]
}

**Comment by Sxyamr** [comment]
![112](https://github.com/alexemanuelol/rustplusplus/assets/68263650/0363e49c-642c-4a6a-a59b-caeca642966c)
Multiple retries, multiple errors

**Comment by 4aGreed** [comment]
same problem

**Comment by 4aGreed** [comment]
can anyone solve this question ? i think maybe its about IP adress

**Comment by 4aGreed** [comment]
This error occurred due to a failure in requesting the Discord API. Therefore, this is likely a connection issue, please ensure that you are not using VPN or proxy and have a stable internet connection. If you think your connection is normal, it is likely that there is a problem with the Discord API. Please try again later

**Comment by 4aGreed** [comment]
![9965](https://github.com/alexemanuelol/rustplusplus/assets/33116562/5a068e27-527a-4fc9-8c39-74a288554911)

**Comment by Sxyamr** [comment]
> This error occurred due to a failure in requesting the Discord API. Therefore, this is likely a connection issue, please ensure that you are not using VPN or proxy and have a stable internet connection. If you think your connection is normal, it is likely that there is a problem with the Discord API. Please try again later

I need to use VPN to connect to Discord, but even though I am using VPN, it still shows an error and cannot work

**Comment by 4aGreed** [comment]
> > 此错误是由于请求 Discord API 失败而发生的。因此，这可能是连接问题，请确保您没有使用 VPN 或代理并且具有稳定的互联网连接。如果您认为您的连接正常，则可能是 Discord API 有问题。请稍后再试
> 
> 我需要使用 VPN 连接到 Discord，但即使我使用的是 VPN，它仍然显示错误并且无法正常工作

yes. because the China net

**Comment by alexemanuelol** [comment]
Feels like it might be unstable connection

**Comment by Sxyamr** [comment]
> Feels like it might be unstable connection
The issue in China may be that I am unable to connect to Discord. I switched to a server in Japan and it can run, but I still want to know how to solve it. Using the server is not very convenient for me

**Comment by joetawil7** [comment]
just type npm i
