### ISSUE TITLE
Trackers @everyone option is not working

### ISSUE THREAD

**Issue by bruhov** [alexemanuelol/rustplusplus#293]
![image](https://github.com/alexemanuelol/rustplusplus/assets/8355561/44ce4916-4c5b-4e36-a628-137838ba2373)
![image](https://github.com/alexemanuelol/rustplusplus/assets/8355561/2a154456-78db-43e3-ac05-5185c3954bda)

**Comment by alexemanuelol** [comment]
Fixed in: 97679cf31fcd0267eefb09a06a5b1a57e12d867a
