### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by Mustafalarcaa** [alexemanuelol/rustplusplus#295]
![Screenshot_5](https://github.com/alexemanuelol/rustplusplus/assets/159753711/d25f2044-5c08-4565-bac7-315264b170fd)

**Comment by C74K** [comment]
node version ?

**Comment by Mustafalarcaa** [comment]
There is no mention of this node installation in the installation video
prepared in Turkish. That's why I couldn't do it. After using this command
and using the commands you gave, the installation is completed.

18 Şub 2024 Paz, saat 23:44 tarihinde C74K ***@***.***> şunu
yazdı:

**Comment by C74K** [comment]
you must have a compatible version of nodejs otherwise it will not work.

**Comment by Mustafalarcaa** [comment]
i did. its didn't work. I explained how I did it.

C74K ***@***.***>, 19 Şub 2024 Pzt, 21:07 tarihinde şunu
yazdı:

**Comment by FaiThiX** [comment]
I tried this and it worked fine:

https://stackoverflow.com/a/59286978/23537473

**Comment by alexemanuelol** [comment]
Yea I think that `npm i -g npm` will solve this in most cases.
