### ISSUE TITLE
Support linux/arm64/v8 

### ISSUE THREAD

**Issue by Derweis** [alexemanuelol/rustplusplus#296]
Hello, I have a raspberry pi 4b and it cannot start. Will there be support for this architecture?

**Comment by MrScruf** [comment]
Had the same issue. Had to compile the docker image myself on my raspberry pi. Then it works, but it is a little more involved then just running one command.

**Comment by Derweis** [comment]
I also assembled it, but on rpi 4b together with hassio it freezes until I restart it manually. Tried it on Orange pi PC there is not enough memory(

**Comment by Derweis** [comment]
Требовалось больше оперативки
