### ISSUE TITLE
some error but nothing about what

### ISSUE THREAD

**Issue by Owned67** [alexemanuelol/rustplusplus#298]
spammed with:
`{"level":"error","message":"2024-3-05 01:04:39 | ERROR: Unhandled Rejection: ,Error: Received one or more errors"}
{"level":"error","message":"2024-3-05 01:05:39 | ERROR: Unhandled Rejection: ,Error: Received one or more errors"}
{"level":"error","message":"2024-3-05 01:07:39 | ERROR: Unhandled Rejection: ,TypeError: Cannot read properties of undefined (reading 'length')"}
{"level":"error","message":"2024-3-05 01:08:39 | ERROR: Unhandled Rejection: ,TypeError: Cannot read properties of undefined (reading 'length')"}`

on DiscordBot.log file.

bot seems working fine so idk what produce this...

using:
npm -v
8.19.2
node -v
v18.12.0

**Comment by C74K** [comment]
some of users have long name ? or you use another language then english ?

**Comment by Owned67** [comment]
> some of users have long name ? or you use another language then english ?

yes ive a long username and my game is in english, server too

**Comment by alexemanuelol** [comment]
It's unfortunate that the error message is so vague :D Ill see if I can improve that in the future to more easily find where the shoe pinches.

Ill close this for now.

**Comment by Owned67** [comment]
get same error but for id now: `{"level":"error","message":"2024-5-11 14:49:26 | ERROR: Unhandled Rejection: ,TypeError: Cannot set properties of undefined (setting 'id')"}`

lol
