### ISSUE TITLE
bot not correctly  say  location on map

### ISSUE THREAD

**Issue by C74K** [alexemanuelol/rustPlusPlus#3]
bot not correctly  say  location on map.
i turn vending on o10 bot say "o11"

**Comment by alexemanuelol** [comment]
Could you take a screenshot of the location of the vending machine on the map?
What is the server name?

**Comment by C74K** [comment]
[RU] Facepunch Hapis

**Comment by C74K** [comment]
and i think after autoserver restart bot dont reconnect to server

**Comment by alexemanuelol** [comment]
I am aware of this, haven't implemented that yet.

**Comment by alexemanuelol** [comment]
Made a bandaid solution to the problem. Please notify me if you ever come across it on another server :)
