### ISSUE TITLE
ERROR: Response contain error property with value: not_found ERROR: Something went wrong with connection.

### ISSUE THREAD

**Issue by lumberzach** [alexemanuelol/rustplusplus#306]
After working flawlessly for a few days, this now happens when I try to connect to any server

Full error:
2024-3-19 17:02:15 440149581028917248 Rustafied.com - US Long III CONNECTED: CONNECTED TO SERVER.
2024-3-19 17:02:15 INFO: Button Interaction - VerifyId: 250680 SUCCESS
2024-3-19 17:02:15 440149581028917248 Rustafied.com - US Long III ERROR: Response contain error property with value: not_found.
2024-3-19 17:02:15 440149581028917248 Rustafied.com - US Long III ERROR: Something went wrong with connection.
2024-3-19 17:02:16 440149581028917248 Rustafied.com - US Long III DISCONNECTED: DISCONNECTED FROM SERVER.

**Comment by alexemanuelol** [comment]
See if you can re-pair the server. Could be that after a wipe they cleared Rust+ data.
