### ISSUE TITLE
Error: connect ETIMEDOUT

### ISSUE THREAD

**Issue by waaynee** [alexemanuelol/rustplusplus#307]
So I followed the docs on the installation part, got it hooked up to discord and ran the bot.
It seems the bot can establish a connection at first, but then looses it and loops in reconnection.

```
2024-3-20 12:56:31 ***** Rusty Moose |EU Monthly| CONNECTING: CONNECTING TO SERVER...
2024-3-20 12:56:31 INFO: Button Interaction - VerifyId: 939701 SUCCESS
2024-3-20 12:56:52 ***** Rusty Moose |EU Monthly| ERROR: Error: connect ETIMEDOUT 168.100.161.48:28082
2024-3-20 12:56:52 ***** Rusty Moose |EU Monthly| ERROR: Could not connect to: 168.100.161.48-28082.
2024-3-20 12:56:52 ***** Rusty Moose |EU Monthly| DISCONNECTED: DISCONNECTED FROM SERVER.
2024-3-20 12:56:53 ***** Rusty Moose |EU Monthly| RECONNECTING: RECONNECTING TO SERVER...
2024-3-20 12:57:08 ***** Rusty Moose |EU Monthly| CONNECTING: CONNECTING TO SERVER...
2024-3-20 12:57:29 ***** Rusty Moose |EU Monthly| ERROR: Error: connect ETIMEDOUT 168.100.161.48:28082
2024-3-20 12:57:29 ***** Rusty Moose |EU Monthly| ERROR: Could not connect to: 168.100.161.48-28082.
2024-3-20 12:57:29 ***** Rusty Moose |EU Monthly| DISCONNECTED: DISCONNECTED FROM SERVER.
2024-3-20 12:57:29 ***** Rusty Moose |EU Monthly| RECONNECTING: RECONNECTING TO SERVER...
2024-3-20 12:57:44 ***** Rusty Moose |EU Monthly| CONNECTING: CONNECTING TO SERVER...
```

Installed NodeJS LTS 20.11.1.
Cloned the git repo at commit [ee00b8e](https://github.com/alexemanuelol/rustplusplus/commit/ee00b8e3a89fc6bc38fcec21f2a1553ae4a1a1f2).

**Comment by alexemanuelol** [comment]
Yea I'm playing that server currently and the same thing happens to me, not sure if Rust+ on the server is bugged or something. Worked fine last wipe

**Comment by waaynee** [comment]
Forgot to mention this was on Windows.
Set it all up again on Ubuntu 20 and NodeJS 21.7.1 and now it runs flawlessly.
Maybe something Win related?

**Comment by alexemanuelol** [comment]
No idea, but I doubt it...

**Comment by waaynee** [comment]
Monitored it for a while. Guess you're right. Seems like it's server related.
