### ISSUE TITLE
Smart switches

### ISSUE THREAD

**Issue by KimViktor522** [alexemanuelol/rustPlusPlus#31]
Can you please add the ability to use one command for multiple switches. For example, I am building a small base with turrets around the house and I want to open them all with one command. Or turn off and turn on all SAMs at once.

**Comment by KimViktor522** [comment]
And one more question, how does the "!timer" command work?

**Comment by alexemanuelol** [comment]
This is already implemented. By running the slash command /switch you can add a switch group.

timer command examples:
!timer add 2h15m This is the timer message
!timer list
!timer remove <ID>

**Comment by KimViktor522** [comment]
I tried using /switch group but when i press turn on or turn off the bot just crashes.
