### ISSUE TITLE
Repeated ExpectedConstraintError When Adding Fields to Embeds

### ISSUE THREAD

**Issue by PR0TX** [alexemanuelol/rustplusplus#310]
Hello,

I get a constant error when the server tries to add fields to an embed using `EmbedBuilder.addFields`.

The process results in an "Unhandled Exception: Error: One or more errors received" message associated with "ExpectedConstraintError" due to an invalid string length repeating every minute as the operation retries.

The problem occurs during the operation, which is indicated by constant one-minute intervals between the error logs, it can be seen in the screenshot.

![Screenshot 2024-04-06 144017](https://github.com/alexemanuelol/rustplusplus/assets/58433688/0659794b-25fa-45fa-9a81-e3d4734fbdb7)

My environment
- Node.js version: 18

Thanks in advance

**Comment by alexemanuelol** [comment]
Looks like it tried to add another field but when field value being empty...
Can you easily reproduce this?

**Comment by PR0TX** [comment]
I definitely haven't figured out yet what causes this error, but it can appear even without commands from the user

**Comment by alexemanuelol** [comment]
Yea I know what causes it, but if you can easily produce the error, I will apply the fix and then you can try again.

**Comment by alexemanuelol** [comment]
Try it now and see if it works better.

**Comment by PR0TX** [comment]
Sorry for not replying for a long time, I updated the server ran it for 2 hours and still no error, thanks
