### ISSUE TITLE
Failed to add bot to voice chat due to TypeError and  Interaction Reply Issues

### ISSUE THREAD

**Issue by PR0TX** [alexemanuelol/rustplusplus#311]
Hello again,

I encountered an error when trying to add a bot to voice chat.The bot is given all permissions, and he has access almost to the server owner

Error details:
ERROR: TypeError: Cannot read properties of undefined (reading 'name')
ERROR: Interaction edit reply failed: ,Error [InteractionNotReplied]: The reply to this interaction has not been sent or deferred.
ERROR: An error occurred while executing this command!

![Screenshot 2024-04-07 022230](https://github.com/alexemanuelol/rustplusplus/assets/58433688/9659cbc1-6c01-4fba-b34d-a2d31ac0ac4d)

![Screenshot 2024-04-07 022303](https://github.com/alexemanuelol/rustplusplus/assets/58433688/eb07b44b-8f98-4a4f-b540-5f8722bdfdef)
"The application is not responding"

Node.js version: 18

Thanks in advance

**Comment by FaiThiX** [comment]
I couldn't reproduce the error but i guess the fix i provided should help with this error

**Comment by alexemanuelol** [comment]
Solved in: de5bc5d37b68f55eb8752e427a2a9175be55f636
