### ISSUE TITLE
Is it possible to provide a more accurate death location when the player dies?

### ISSUE THREAD

**Issue by Ayuan97** [alexemanuelol/rustplusplus#312]
For example, within a square grid, you can treat it as a smaller nine-square grid, and you can obtain a more precise position of the player in a certain coordinate, such as coordinate information such as M19-1 M19-5.

**Comment by Versette** [comment]
I think that would be a bit confusing..
I'll look into making it so it divides it into top left, middle, right, etc. and will probably submit a PR.

**Comment by Ayuan97** [comment]
> I think that would be a bit confusing.. I'll look into making it so it divides it into top left, middle, right, etc. and will probably submit a PR.

You can understand a square as 123456789 on the numeric keyboard, so that you can get a more accurate position of the player.
