### ISSUE TITLE
FCM无内容 无法工作

### ISSUE THREAD

**Issue by a123dgf** [alexemanuelol/rustplusplus#320]
![64879cdc17702479a2ec3fb5dee9fc4](https://github.com/alexemanuelol/rustplusplus/assets/168752247/627dc3c5-86a8-4725-8be3-debe2ef76da0)
I've tried to log back in several times and he doesn't work

**Comment by FaiThiX** [comment]
i guess your from china? if so china is blocking fcm/gcm because its a google push notification thing. check your vpn software if it allows apps to bypass the vpn. if not i dont know how to fix it right now

**Comment by a123dgf** [comment]
Thank you for your answer, but I am unable to successfully operate FCM in Hong Kong, China

**Comment by FaiThiX** [comment]
@Trophy198 released a tool that will work even in china if you can use a vpn in your browser that is outside china. I tested it with a mate of mine who is located in china.

https://rustplusplus-credentials.netlify.app/
