### ISSUE TITLE
Unable to pair smart switch with bot

### ISSUE THREAD

**Issue by Alex25482** [alexemanuelol/rustplusplus#323]
When I make a pair attempt to a smart switch nothing happens in the switches page on discord.
I can see a JSON output in the terminal running the NPM server that suggests the bot was able to see the pair attempt but nothing appears in discord.
![image](https://github.com/alexemanuelol/rustplusplus/assets/165504991/085554f0-2452-4082-90b6-57fcfda9c5f7)

Everything apart from the smart device functionality is working, including in game commands (e.g. !time) and the information page showing team/server info.

I have been able to pair smart switch's in the past and them appear in discord, don't know why it isn't working now.
I also tried deleting and re-doing credential just in case.

**Comment by alexemanuelol** [comment]
Fixed last week in: 7e77a859a9351fc410b8d6bcafdedcafca4a0877
