### ISSUE TITLE
Program not working after 'npm start run'

### ISSUE THREAD

**Issue by Allerek** [alexemanuelol/rustplusplus#326]
![image](https://github.com/alexemanuelol/rustplusplus/assets/12304071/764b7e3a-ac96-4374-93fd-9807a9cd0e90)
Im getting stuck here, i set-up config/index.js correctly

**Comment by Allerek** [comment]
Tried both node.js 18 and 20 (LTS caused crash at start)

**Comment by msugenius** [comment]
Hey!
I may be misunderstanding you, but from the looks of it the app is already working. Check if the bot is currently running and provide a log, please, if it isn`t.

**Comment by alexemanuelol** [comment]
On bad machines this can currently take a while. At that stage its reading rustlabs data files. Those files are quite big. I will in the future make it possible to disable the rustlabs functionality in the config. As to your "problem", give it a few minutes.
