### ISSUE TITLE
[idea] Add additional information

### ISSUE THREAD

**Issue by MrFiNka** [alexemanuelol/rustplusplus#328]
1. When a person goes to afk, add a message in which square he came out and RT
2. Make a command to force code in afk
3. Make commands to see how long it takes for the crate to open on oil rigs
4. Try to implement the event of oblomov (Bradley APC) it is desirable to create an event and calculate when Bradley will be extinguished and it will be possible to pick up the boxes

5. When rust+ manages to get the nickname and steamid of the player who killed you, write additional information in the activity

For some reason, sometimes there is a spam of events or activity, I will attach a photo, please fix it
![upload_2024_05_20_17_51_09_220](https://github.com/alexemanuelol/rustplusplus/assets/48646488/d7946cd8-6db9-43fb-a49b-69d197cde949)

**Comment by FaiThiX** [comment]
> 1. When a person goes to afk, add a message in which square he came out and RT
> 2. Make a command to force code in afk
> 3. Make commands to see how long it takes for the crate to open on oil rigs
> 4. Try to implement the event of oblomov (Bradley APC) it is desirable to create an event and calculate when Bradley will be extinguished and it will be possible to pick up the boxes
> 5. When rust+ manages to get the nickname and steamid of the player who killed you, write additional information in the activity
> 
> For some reason, sometimes there is a spam of events or activity, I will attach a photo, please fix it !

1. for what reason? i guess its ok to see that someone is afk
2. dont know what you mean by that
3./4. Facepunch removed that from Rust+ so we cant implement it, we had it back when it was provided [Rust DevBlog for Rust+ Nerfs](https://rust.facepunch.com/news/r-u-s-t#RustChanges)
5. Name and Steamid is only send to Rust+ if you are killed while being offline. If you're online there is nothing send with additional information
6. cant reproduce it so i dont know why it does it and i cant fix it.
