### ISSUE TITLE
Smart switch pairing error

### ISSUE THREAD

**Issue by msugenius** [alexemanuelol/rustplusplus#329]
### Hey!
I play on the Rustafied US Long III server and have been using a bot for the past two months. My experience has been great until the last wipe. However, after the wipe on May 2, the bot stopped displaying smart switches even though the Rust+ app has them.
What I tried doing:
- Remove the server from the bind list in the bot and add it again (didn't help)
- Completely clear all app volumes and restart it (didn't help)

Screenshot of empty switches channel:
![Screenshot](https://github.com/alexemanuelol/rustplusplus/assets/72615150/da3b6642-cac9-4ded-bd2b-69bfb43f2725)

Screenshot of Rust+ companion app with switches: 
![Screenshot](https://github.com/alexemanuelol/rustplusplus/assets/72615150/5b56531c-ae8c-447f-ac6a-6f7a269d371d)

### Environment:
OS: Ubuntu 22.04.3 LTS (GNU/Linux 5.15.0-107-generic x86_64)
Deploy method: Docker compose stack
Docker version: 24.0.5, build ced0996x
Docker Compose version: v2.20.2
Bot version: [a9d885a](https://github.com/alexemanuelol/rustplusplus/commit/a9d885a9e31887c39651973e2e0f3a4c259c1c21)

### Logs
Example message when pairing a smart switch (switch successfully paired to Rust+ but isn`t listed in bot)

```bash
rust-plus-plus-rpp-1  | 2024-5-18 17:12:30 FCM Host: GuildID: 1226990040232755270, SteamID: myId, pairing: entity: other
rust-plus-plus-rpp-1  | {"data":{"experienceId":"@facepunch/RustCompanion","scopeKey":"@facepunch/RustCompanion","body":"{\"img\":\"https:\\/\\/cdn.rustafied.systems\\/server-header-images\\/US Long 3.png\",\"entityType\":\"1\",\"ip\":\"104.143.2.103\",\"entityId\":\"1066116940\",\"type\":\"entity\",\"url\":\"https:\\/\\/forum.rustafied.com\\/store\\/product\\/16-us-long-iii\\/\",\"playerToken\":\"myToken\",\"port\":\"28017\",\"entityName\":\"Smart Switch\",\"name\":\"Rustafied.com - US Long III\",\"logo\":\"\",\"id\":\"ff689992-14c8-4dfb-96e1-c4bb99fea218\",\"desc\":\"Wipe: Monthly on Thursdays @ 3PM New York time (or when forced)\\\\nBase Pop: 200+ players | Map size: 4000 | BP Wipe: NO BP wipe\\\\n\\\\n\\\\tREPORT A PLAYER: my.rustafied.com or in-game using \\/report\\\\n\\\\n\\\\tSTORE: rustafied.com\\/store\\\\t\\\\t|\\\\tSUPPORT: rustafied.com\\/support\\\\n\\\\tRULES: rustafied.com\\/rules\\\\t\\\\t|\\\\tDISCORD: discord.gg\\/rustafied\\\\n\\\\nWhat to expect:\\\\n\\\\t- High quality gameplay and player experience\\\\n\\\\t- Player based map voting for upcoming wipes\\\\n\\\\t- Custom anti-cheat and active server moderation\\\\n\\\\t- Hosted on the\",\"playerId\":\"myId\"}","message":"Tap to pair with this device.","title":"Smart Switch","projectId":"49451aca-a822-41e6-ad59-955718d0ff9c","channelId":"pairing"},"from":"976529667804","priority":"high","fcmMessageId":"ec5a70f0-1c75-4036-9764-e4e81ad1ca65"}
rust-plus-plus-rpp-1  | 2024-5-18 17:14:38 FCM Host: GuildID: 1226990040232755270, SteamID: myId, pairing: entity: other
rust-plus-plus-rpp-1  | {"data":{"experienceId":"@facepunch/RustCompanion","scopeKey":"@facepunch/RustCompanion","body":"{\"img\":\"https:\\/\\/cdn.rustafied.systems\\/server-header-images\\/US Long 3.png\",\"entityType\":\"\"ip\":\"104.143.2.103\",\"entityId\":\"1066116940\",\"type\":\"entity\",\"url\":\"https:\\/\\/forum.rustafied.com\\/storproduct\\/16-us-long-iii\\/\",\"playerToken\":\"myToken\",\"port\":\"28017\",\"entityName\":\"Smart Switc\"name\":\"Rustafied.com - US Long III\",\"logo\":\"\",\"id\":\"ff689992-14c8-4dfb-96e1-c4bb99fea218\",\"desc\":\"WipMonthly on Thursdays @ 3PM New York time (or when forced)\\\\nBase Pop: 200+ players | Map size: 4000 | BP Wipe: NOwipe\\\\n\\\\n\\\\tREPORT A PLAYER: my.rustafied.com or in-game using \\/report\\\\n\\\\n\\\\tSTORE: rustafied.costore\\\\t\\\\t|\\\\tSUPPORT: rustafied.com\\/support\\\\n\\\\tRULES: rustafied.com\\/rules\\\\t\\\\t|\\\\tDISCORD: discorgg\\/rustafied\\\\n\\\\nWhat to expect:\\\\n\\\\t- High quality gameplay and player experience\\\\n\\\\t- Player basedvoting for upcoming wipes\\\\n\\\\t- Custom anti-cheat and active server moderation\\\\n\\\\t- Hosted on th\"playerId\":\"myId\"}","message":"Tap to pair with this device.","title":"Smart Switch","projectId":"49451aca-a822-41e6-ad59-955718d0ff9c","channelId":"pairing"},"from":"976529667804","priority":"high",
"fcmMessageId":"e0ab3f36-7aa8-40e7-83cb-d68a3684df8e"}
```

### Additional
If necessary, I can add additional information, (logs, screenshots, etc.)

**Comment by alexemanuelol** [comment]
This is already fixed on master, haven't made a new docker build tho

**Comment by msugenius** [comment]
Okay, thanks, I'll build an image from the source code.

**Comment by internoot** [comment]
@msugenius any docs or pointers on rebuilding the docker image from source? I am also experiencing this in a dockerised deployment.

**Comment by msugenius** [comment]
Hi, @internoot! 
It's very simple, the algorithm is:
```bash
git clone https://github.com/alexemanuelol/rustplusplus.git
cd rustplusplus
```
Then add `build` in `docker-compose.yml` instead of `image `, so your compose file looks like this:
```bash
services:
    app:
        volumes:
            - ./credentials:/app/credentials
            - ./instances:/app/instances
            - ./logs:/app/logs
            - ./maps:/app/maps
        environment:
            - RPP_DISCORD_CLIENT_ID=111....1111
            - RPP_DISCORD_TOKEN=token
        container_name: rpp
        build:
            context: .
            dockerfile: Dockerfile
```
Then you can set your environment variables directly in compose file, or in .env file. If you want to use .env you need update compose file a little bit:
```bash
services:
    app:
        volumes:
            - ./credentials:/app/credentials
            - ./instances:/app/instances
            - ./logs:/app/logs
            - ./maps:/app/maps
        environment:
            - RPP_DISCORD_CLIENT_ID=${RPP_DISCORD_CLIENT_ID}
            - RPP_DISCORD_TOKEN=${RPP_DISCORD_TOKEN}
        container_name: rpp
        build:
            context: .
            dockerfile: Dockerfile
```
And ofc declare those vars in .env file:
```bash
RPP_DISCORD_CLIENT_ID=id
RPP_DISCORD_TOKEN=token
```

And finally you can run your bot using 
```bash
docker compose up -d
```

I hope my comment clear enough, but if you still have any questions I`ll answer it as fast as possible.

**Comment by internoot** [comment]
@msugenius thanks! I will give this a go tonight :-)

**Comment by internoot** [comment]
> Hi, @internoot! It's very simple, the algorithm is:
> 
> ```shell
> git clone https://github.com/alexemanuelol/rustplusplus.git
> cd rustplusplus
> ```
> 
> Then add `build` in `docker-compose.yml` instead of `image `, so your compose file looks like this:
> 
> ```shell
> services:
>     app:
>         volumes:
>             - ./credentials:/app/credentials
>             - ./instances:/app/instances
>             - ./logs:/app/logs
>             - ./maps:/app/maps
>         environment:
>             - RPP_DISCORD_CLIENT_ID=111....1111
>             - RPP_DISCORD_TOKEN=token
>         container_name: rpp
>         build:
>             context: .
>             dockerfile: Dockerfile
> ```
> 
> Then you can set your environment variables directly in compose file, or in .env file. If you want to use .env you need update compose file a little bit:
> 
> ```shell
> services:
>     app:
>         volumes:
>             - ./credentials:/app/credentials
>             - ./instances:/app/instances
>             - ./logs:/app/logs
>             - ./maps:/app/maps
>         environment:
>             - RPP_DISCORD_CLIENT_ID=${RPP_DISCORD_CLIENT_ID}
>             - RPP_DISCORD_TOKEN=${RPP_DISCORD_TOKEN}
>         container_name: rpp
>         build:
>             context: .
>             dockerfile: Dockerfile
> ```
> 
> And ofc declare those vars in .env file:
> 
> ```shell
> RPP_DISCORD_CLIENT_ID=id
> RPP_DISCORD_TOKEN=token
> ```
> 
> And finally you can run your bot using
> 
> ```shell
> docker compose up -d
> ```
> 
> I hope my comment clear enough, but if you still have any questions I`ll answer it as fast as possible.

Just updating that this worked perfectly, thanks for your help
