### ISSUE TITLE
Support for voice

### ISSUE THREAD

**Issue by alexemanuelol** [alexemanuelol/rustplusplus#33]
Make it possible for the bot to join voice chat and notify events/alarms/other notifications.

**Comment by goldbeg** [comment]
> Make it possible for the bot to join voice chat and notify events/alarms/other notifications.

Suggestion for you mate, Use FFMPEG to play .mp3 files containing TTS such as "Smart Alarm Triggered; ect"

Some [Easy Examples](https://stackoverflow.com/questions/41580798/how-to-play-audio-file-into-channel) to Follow! 

Love to see this in the near future!

**Comment by FaiThiX** [comment]
currently working on this Enhancement
https://github.com/FaiThiX/rustplusplus/tree/voice

**Comment by FaiThiX** [comment]
#204 is ready to be reviewed ;)

**Comment by alexemanuelol** [comment]
Added in: ec618e04153bd5acf37fc39aa4f760787da3983a

**Comment by goldbeg** [comment]
1 year later

**Comment by FaiThiX** [comment]
It's already implemented ;)

**Comment by alexemanuelol** [comment]
> 1 year later

What are you implying?
