### ISSUE TITLE
(Idea) Interactive Map

### ISSUE THREAD

**Issue by Stevanr21** [alexemanuelol/rustplusplus#332]
I have an idea that I think might be useful, I saw it somewhere but I don't remember where. An interactive game map, hosted on a local website that works with the bot and shows the map in real time, like Rust+ does, showing connected players, where they are, and so on. I hope it can be done, it occurred to me :D

**Comment by alexemanuelol** [comment]
I think it might be too complex, having to host a website for each instance of the bot, not ideal.
