### ISSUE TITLE
TypeError: Cannot read properties of undefined

### ISSUE THREAD

**Issue by itsPhysikz** [alexemanuelol/rustplusplus#333]
![4vT8z7u](https://github.com/alexemanuelol/rustplusplus/assets/147779658/43989dda-0c71-41a6-b1d5-3d7ad0810bf1)

let me know if anyone knows whats wrong here. thanks :)

started happening after rust update 6/6.

**Comment by lost896** [comment]
same

**Comment by FaiThiX** [comment]
try to disconnect and reconnect the rust++ bot to the server. if that doesnt work maybe try to remove the server and repair the server.
