### ISSUE TITLE
Custom icon bot

### ISSUE THREAD

**Issue by nachogrxdev** [alexemanuelol/rustPlusPlus#336]
I modified the bot icon from the Discord developers panel, but upon restarting the bot he lost the icon and banner set through this panel.
Is there a way to set these images as default from my docker instance?

**Comment by Trophy198** [comment]
> I modified the bot icon from the Discord developers panel, but upon restarting the bot he lost the icon and banner set through this panel. Is there a way to set these images as default from my docker instance?

This is an open-source project. if you want change avatar, You can change the profile by directly modifying the profile URL in the setAvatar logic.
