### ISSUE TITLE
Roles and permissions reset when restarting docker

### ISSUE THREAD

**Issue by nachogrxdev** [alexemanuelol/rustplusplus#343]
I am currently experiencing that when I restart the docker server I lose the custom permissions set on certain channels. For example, the configuration channel, team chat and some others, only I have permission to see said channel and all the others, any member of a group can see them.
How could I maintain this configuration of roles and permissions on each reboot?

Thanks!

**Comment by alexemanuelol** [comment]
Currently you can use the /role command to to restrict the channels to that role. Whatever custom roles you set will be removed on a bot restart.
