### ISSUE TITLE
[Idea] Switch from RustLabs to RustHelp once it's released

### ISSUE THREAD

**Issue by someC0d3r** [alexemanuelol/rustplusplus#345]
Since RustHelp.com isn't released yet this ticket is more of an idea than an actual issue -> just something for the backlog as a reminder.

There was / is currently a controversy since RustLabs got sold to RustClash:
https://www.reddit.com/r/playrust/comments/1dvkyg6/rustlabscom_is_now_wikirustclashcom/
https://www.reddit.com/r/playrust/comments/1dwnvkj/rustlabcom_bought_out_by_rust_clash_please_avoid/

Therefore hoppel announced RustHelp:
https://www.reddit.com/r/playrust/comments/1dwv0jd/since_rustlabs_sold_out_ill_drop_this_here/

Once RustHelp is out, it should be checked what it is capable of and maybe RustPlusPlus can shift it's current functionality which is based on RustLabs to RustHelp. 

RustHelp release:
An admin of the Discord server of RustHelp announced that the site will probably be released at the end of the month.

RustHelp site:
https://rusthelp.com/

What are your thoughts?

**Comment by Nikolassparrow** [comment]
hoppel is known for being anti-consumer and actually charging for basic services (rustmaps). although rustlabs selling out to rustclash is cringe, in my opinion, it should remain on rustlabs.

**Comment by hoppel** [comment]
Hey! Gonna be a little bit off-topic, sorry about that, but I do wanna "defend myself"

> hoppel is known for being anti-consumer and actually charging for basic services (rustmaps). although rustlabs selling out to rustclash is cringe, in my opinion, it should remain on rustlabs.

RustMaps (previously rustmg.io) released roughly 4 years ago, we introduced paid plans in February this year, so we were running it for roughly 3 1/2 years out of our own pocket. Personally, I don't think charging for a service that costs well more than 1k USD a month to run is anti-consumer. 


>
> I was naive and only saw the "API" link on RustMaps and thought that there will be a public accessible API - because of that I concluded that RustHelp may have also some public API.
> 
> Nevertheless I didn't investigate further. It seems you need to have an API key, but I don't know how to get that or what conditions must be met to get that key. :/

After logging in anyone can get an API key here https://rustmaps.com/dashboard - API is free to use generally, but some API routes are for features that do require a subscription.


Now, for RustHelp, initially the site will not have an API at launch, later on there will definitely be an API which could be used by this project.

**Comment by alexemanuelol** [comment]
Im all for changing to something else since I really hate gambling. Will probably reside to scraping some other website that have good enough Rust info. The only script that needs changing is the external "process_rustlabs.js". rustplusplus does not request info from the site in real-time, it relies on pre-compiled json files with all the data updated (by me) each month. We'll see what will be done and when.
