### ISSUE TITLE
Need help with bot Rust+

### ISSUE THREAD

**Issue by focuszz11** [alexemanuelol/rustplusplus#346]
After running the bot and all the settings, I linked Rust+ via https://github.com/alexemanuelol/rustPlusPlus-Credential-Application/releases/, but when I click link Rust+, the message to the bot for linking does not come. Could you help with this?

**Comment by C74K** [comment]
https://rustplusplus-credentials.netlify.app/

**Comment by focuszz11** [comment]
I explained myself a little incorrectly. When I press the bind Rust+ button in the game, the message does not come to the bot, although I am authorized in the bot.
