### ISSUE TITLE
need help with connecting server in bot

### ISSUE THREAD

**Issue by focuszz11** [alexemanuelol/rustplusplus#348]
Hello, after all the bindings and authorization in Rust+ (either through the application or through the web version) (Receiving FCM credentials, the bot confirms that the account is bound), when pressing the button in the Pair with Server game, a message about the binding does not come in the bot, but on the phone the server binding in the Rust+ application comes. Could you help with this?

**Comment by MrFiNka** [comment]
Make sure you're logged in to the same Steam account

**Comment by focuszz11** [comment]
I definitely linked the right steam account

**Comment by C74K** [comment]
> Hello, after all the bindings and authorization in Rust+ (either through the application or through the web version) (Receiving FCM credentials, the bot confirms that the account is bound), when pressing the button in the Pair with Server game, a message about the binding does not come in the bot, but on the phone the server binding in the Rust+ application comes. Could you help with this?

are you have rust+ app on phone ?

**Comment by focuszz11** [comment]
да

**Comment by C74K** [comment]
> yes

if you pair server you have info on phone about it but not in bot ?

**Comment by focuszz11** [comment]
> > да
> 
> если вы подключаете сервер, у вас есть информация об этом на телефоне, но нет в боте?

Yes that's right

**Comment by C74K** [comment]
it means that you have not connected the bot to your steam account.

**https://rustplusplus-credentials.netlify.app/**

**Comment by C74K** [comment]
https://rustplusplus-credentials.netlify.app/documents/getting-started/fcm-credentials

**Comment by focuszz11** [comment]
I already did this a long time ago.
![image](https://github.com/user-attachments/assets/ec0dd957-24ee-447a-81ea-4230e3fe4219)

**Comment by maxcutie** [comment]
having the same issue, cant link to the bot even though everything is set up correctly

**Comment by heyimjonas** [comment]
`2024-8-03 18:40:58 351706639491006464 Rusty Moose |EU Monthly| CONNECTING: CONNECTING TO SERVER...
2024-8-03 18:40:58 351706639491006464 Rusty Moose |EU Monthly| CONNECTED: CONNECTED TO SERVER.
2024-8-03 18:40:59 351706639491006464 Rusty Moose |EU Monthly| ERROR: Response contain error property with value: not_found.
2024-8-03 18:40:59 351706639491006464 Rusty Moose |EU Monthly| ERROR: Something went wrong with connection.
2024-8-03 18:40:59 INFO: Button Interaction - VerifyId: 606011 SUCCESS
2024-8-03 18:41:03 351706639491006464 Rusty Moose |EU Monthly| DISCONNECTED: DISCONNECTED FROM SERVER.
`

I get the same error.

1. I reset the bot on my VPS.
2. Opened ports.
3. Reset the discord bot.
4. Reset the connection.
5 Reset the FCM thing.
6. tried multiple time to re-pair the server.

I get this error on different servers.

**Comment by bset-302** [comment]
I'm receiving a similar issue - I never get prompted to pair the server within the discord channel. It worked fine a couple of months ago. 

The only potential issue I see in the logs is this -

`
`2024-8-15 18:06:23 WARNING: FCM Credentials are not registered for guild: 12736953362********, cannot start FCM-listener.`
`

**Comment by heyimjonas** [comment]
> `2024-8-03 18:40:58 351706639491006464 Rusty Moose |EU Monthly| CONNECTING: CONNECTING TO SERVER... 2024-8-03 18:40:58 351706639491006464 Rusty Moose |EU Monthly| CONNECTED: CONNECTED TO SERVER. 2024-8-03 18:40:59 351706639491006464 Rusty Moose |EU Monthly| ERROR: Response contain error property with value: not_found. 2024-8-03 18:40:59 351706639491006464 Rusty Moose |EU Monthly| ERROR: Something went wrong with connection. 2024-8-03 18:40:59 INFO: Button Interaction - VerifyId: 606011 SUCCESS 2024-8-03 18:41:03 351706639491006464 Rusty Moose |EU Monthly| DISCONNECTED: DISCONNECTED FROM SERVER. `
> 
> I get the same error.
> 
>     1. I reset the bot on my VPS.
> 
>     2. Opened ports.
> 
>     3. Reset the discord bot.
> 
>     4. Reset the connection.
>        5 Reset the FCM thing.
> 
>     5. tried multiple time to re-pair the server.
> 
> 
> I get this error on different servers.

i fixed it by resetting the bot from the ground up. i didn't modify any settings and the first thing i did was setting up the credentials and then did customization. this way it worked for me.

**Comment by LShirohana** [comment]
Update: While connected to the server, I hit the "Resend pairing notification" button and... it worked. I do not really get it.

**Comment by alexemanuelol** [comment]
> Update: While connected to the server, I hit the "Resend pairing notification" button and... it worked. I do not really get it.

https://github.com/alexemanuelol/rustplusplus/blob/master/FAQ.md#credentials-added-but-no-pair-notification
