### ISSUE TITLE
How to control streamer mode in server?

### ISSUE THREAD

**Issue by hollandtoby** [alexemanuelol/rustplusplus#357]
Hi Alex, thank you so much for all your work and for sharing it freely. It's so awesome. 

How do I change this "streamer mode" to off or is it a server setting? I'd like to see the real names in the information panel. Thanks

![image](https://github.com/user-attachments/assets/5f90fb34-96b3-4a97-a0e2-cbfa7aaeec77)

![image](https://github.com/user-attachments/assets/e5ab7848-f760-47fb-9a8e-8eaa56563c86)

**Comment by MrFiNka** [comment]
These are server settings, you can't influence them

**Comment by alexemanuelol** [comment]
These things are set on server config. Only admins can change that setting.
