### ISSUE TITLE
[ERROR} Duplicated messages

### ISSUE THREAD

**Issue by MrFiNka** [alexemanuelol/rustplusplus#364]
For some reason, messages are sometimes duplicated. Please correct them.

Messages are also written in the game
![image](https://github.com/user-attachments/assets/dff36b09-5ea2-40f6-b523-47700e573dc2)

**Comment by Zuescho** [comment]
Try pairing again and make sure it's only paired once to the server.

I had this happened once because it was pared multiply times, also, please work on your tone in requests, the way you have written this right now the tone is quite demanding for something that is provided for free.

**Comment by alexemanuelol** [comment]
Bug when multiple instances of the bot are running at the same time
