### ISSUE TITLE
Add support for multiple languages

### ISSUE THREAD

**Issue by alexemanuelol** [alexemanuelol/rustPlusPlus#37]

**Comment by C74K** [comment]
where is language files location ?

**Comment by alexemanuelol** [comment]
Does not exist.

**Comment by C74K** [comment]
i try tranlate and bot stoped working

**Comment by alexemanuelol** [comment]
Well if you try to modify the code and it stops working, that's on you. That has nothing to do with this issue.

**Comment by alexemanuelol** [comment]
Added in c54df26943cc1154ada73244913ed3d2f5186e13
