### ISSUE TITLE
BOT not reconnecting after server restart.

### ISSUE THREAD

**Issue by C74K** [alexemanuelol/rustPlusPlus#4]
After autoserver restart bot dont reconnect to server.

**Comment by alexemanuelol** [comment]
I am aware of this, not implemented yet.

**Comment by C74K** [comment]
ok w8 on add this

**Comment by alexemanuelol** [comment]
Added 2 days ago

**Comment by C74K** [comment]
works after rust serwer restart ??
 ok i check later.

**Comment by alexemanuelol** [comment]
Yea, should do :)
