### ISSUE TITLE
Bradley APC null before respawn.

### ISSUE THREAD

**Issue by ItsCalebJones** [alexemanuelol/rustPlusPlus#43]
The timer for Bradley's respawn appears to not be getting set, funnily enough if you run the command to check the timer it does return.

![image](https://user-images.githubusercontent.com/4519230/175045358-039b0d0e-d2f0-4595-9579-b13cb59074d3.png)

**Comment by alexemanuelol** [comment]
Fixed in 4646673fad2a3871f0216b5bd7e4c4ac9ba64c37
