### ISSUE TITLE
- Battlemetrics Player Tracker 'xxx' does not exist.

### ISSUE THREAD

**Issue by maxmacer** [alexemanuelol/rustPlusPlus#45]
When trying to add a new player tracker, no matter what the bot returns that it doesn't exist
/tracker add_player tracker_name:(tracker name) steam_id:(steam id) returns:
 Battlemetrics Player Tracker 'name' does not exist.

**Comment by alexemanuelol** [comment]
You probably havent clicked on 'CREATE TRACKER' from the servers channel for that server. The 'CREATE TRACKER' button is only available if the server is not streamer mode.
