### ISSUE TITLE
8 vulnerabilities (6 moderate, 1 high, 1 critical)

### ISSUE THREAD

**Issue by Owned67** [alexemanuelol/rustPlusPlus#47]
npm i return:
`~/rustPlusPlus$ npm i

up to date, audited 286 packages in 7s

19 packages are looking for funding
  run `npm fund` for details

8 vulnerabilities (6 moderate, 1 high, 1 critical)

To address all issues, run:
  npm audit fix

Run `npm audit` for details.
:~/rustPlusPlus$ npm audit fix

up to date, audited 286 packages in 3s

19 packages are looking for funding
  run `npm fund` for details

# npm audit report

jpeg-js  <=0.4.3
Severity: high
Uncontrolled resource consumption in jpeg-js - https://github.com/advisories/GHSA-w7q9-p3jq-fmhm
Infinite loop in jpeg-js - https://github.com/advisories/GHSA-xvf7-4v9q-58w6
fix available via `npm audit fix`
node_modules/jpeg-js
  @jimp/jpeg  <=0.12.0
  Depends on vulnerable versions of jpeg-js
  node_modules/@jimp/jpeg
    @jimp/types  <=0.11.1-canary.891.908.0
    Depends on vulnerable versions of @jimp/jpeg
    node_modules/@jimp/types
      jimp  0.3.6-alpha.5 - 0.11.1-canary.891.908.0
      Depends on vulnerable versions of @jimp/custom
      Depends on vulnerable versions of @jimp/types
      node_modules/jimp

minimist  <=1.2.5
Severity: critical
Prototype Pollution in minimist - https://github.com/advisories/GHSA-xvch-5gv4-984h
Prototype Pollution in minimist - https://github.com/advisories/GHSA-vh95-rmgr-6w4m
fix available via `npm audit fix`
node_modules/minimist
  mkdirp  0.4.1 - 0.5.1
  Depends on vulnerable versions of minimist
  node_modules/mkdirp
    @jimp/core  <=0.9.6-canary.860.700.0
    Depends on vulnerable versions of mkdirp
    node_modules/@jimp/core
      @jimp/custom  <=0.8.6-canary.818.495.0 || 0.9.2-canary.815.538.0 - 0.9.3-canary.825.599.0 || 0.9.4-canary.832.606.0 - 0.9.4-canary.845.627.0 || 0.9.6-canary.857.681.0 - 0.9.6-canary.860.700.0
      Depends on vulnerable versions of @jimp/core
      node_modules/@jimp/custom

8 vulnerabilities (6 moderate, 1 high, 1 critical)`

npm 8.13.2
node v18.6.0
debian bulleyes

**Comment by alexemanuelol** [comment]
Fixed in 735d041 and fb07279
