### ISSUE TITLE
Smart Switch not showing up in #switches on pair

### ISSUE THREAD

**Issue by andrewdens** [alexemanuelol/rustPlusPlus#48]
When pairing a smart switch it isn't showing up in the #switches channel. Not sure where to look to find logs or anything.

**Comment by alexemanuelol** [comment]
Have you set credentials? Paired the server? Connected to the server?

**Comment by andrewdens** [comment]
Yes, from what I can tell everything is working. I can see events, teamchat, information, etc.

**Comment by alexemanuelol** [comment]
Could it be that you have used the mobile app im between?

**Comment by andrewdens** [comment]
Yes I have, does that interfere somehow with the discord pair

**Comment by alexemanuelol** [comment]
Yea, sometimes it can be problematic, just try to generate new credentials

**Comment by andrewdens** [comment]
Ok I'll try that thanks

**Comment by andrewdens** [comment]
I'm getting this warning when trying to set the new credentials to the discord server. Do i need to remake a new discord server?  WARNING: FCM Credentials are already used for another discord server!

**Comment by C74K** [comment]
delete credential config file in bot folder

**Comment by alexemanuelol** [comment]
No you dont have to delete the folder, just run the credentials clear command

**Comment by andrewdens** [comment]
I've cleared the credentials and repaired with new credentials and this message comes up but still nothing showing on discord. 2022-8-01 20:07:40 FCM: <###################> pairing: entity: Switch

**Comment by andrewdens** [comment]
After clearing the credentials and repairing the server it comes up now. Thanks!
