### ISSUE TITLE
Make your bot multi server

### ISSUE THREAD

**Issue by aziz191546** [alexemanuelol/rustPlusPlus#5]
Like anyone you can add server IP and get notification and all commands

**Comment by alexemanuelol** [comment]
Do you mean that the bot can be used over several discord servers or do you mean multiple rust servers connected on one discord server?

**Comment by aziz191546** [comment]
multiple rust servers and multiple discord servers

**Comment by alexemanuelol** [comment]
The current implementation allows ONE connected rust server per discord server, but there is a list of previously connected rust server where you can easily switch between rust servers. And the current implementation also allows the bot to be invited to multiple discord servers.
