### ISSUE TITLE
npm install fails

### ISSUE THREAD

**Issue by HoeblingerDaniel** [alexemanuelol/rustPlusPlus#50]
After commit 735d0412121f03ce1693b43c37e5741d1aadba3f npm install fails and outputs Invalid Version: ^0.4.4.
This should be the package jpeg-js.

This is the important part of the log: 
`silly fetch manifest jpeg-js@0.4.2
41 http fetch GET 200 https://registry.npmjs.org/jpeg-js 12ms (cache hit)
42 timing idealTree Completed in 132ms
43 timing command:install Completed in 142ms
44 verbose stack TypeError: Invalid Version: ^0.4.4
44 verbose stack     at new SemVer (C:\Program Files\nodejs\node_modules\npm\node_modules\semver\classes\semver.js:38:13)
44 verbose stack     at compare (C:\Program Files\nodejs\node_modules\npm\node_modules\semver\functions\compare.js:3:32)
44 verbose stack     at Object.gte (C:\Program Files\nodejs\node_modules\npm\node_modules\semver\functions\gte.js:2:30)
44 verbose stack     at CanPlaceDep.checkCanPlaceCurrent (C:\Program Files\nodejs\node_modules\npm\node_modules\@npmcli\arborist\lib\can-place-dep.js:173:51)
44 verbose stack     at CanPlaceDep.checkCanPlace (C:\Program Files\nodejs\node_modules\npm\node_modules\@npmcli\arborist\lib\can-place-dep.js:157:27)
44 verbose stack     at new CanPlaceDep (C:\Program Files\nodejs\node_modules\npm\node_modules\@npmcli\arborist\lib\can-place-dep.js:114:26)
44 verbose stack     at PlaceDep.place (C:\Program Files\nodejs\node_modules\npm\node_modules\@npmcli\arborist\lib\place-dep.js:121:19)
44 verbose stack     at new PlaceDep (C:\Program Files\nodejs\node_modules\npm\node_modules\@npmcli\arborist\lib\place-dep.js:71:10)
44 verbose stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\build-ideal-tree.js:984:31
44 verbose stack     at Array.map (<anonymous>)
45 verbose cwd C:\Users\MyUser\Desktop\rustPlusPlus
46 verbose Windows_NT 10.0.22579
47 verbose node v18.0.0
48 verbose npm  v8.6.0
49 error Invalid Version: ^0.4.4
50 verbose exit 1`

**Comment by alexemanuelol** [comment]
I reverted the jpeg-js version to 0.4.3 instead, hope that will work better.

**Comment by C74K** [comment]
downloade and dont work this same error
