### ISSUE TITLE
npm ERR! Invalid Version: ^0.4.3

### ISSUE THREAD

**Issue by C74K** [alexemanuelol/rustPlusPlus#51]
0 verbose cli C:\Program Files\nodejs\node.exe C:\Users\CZAK_Games\AppData\Roaming\npm\node_modules\npm\bin\npm-cli.js
1 info using npm@8.16.0
2 info using node@v16.16.0
3 timing npm:load:whichnode Completed in 0ms
4 timing config:load:defaults Completed in 1ms
5 timing config:load:file:C:\Users\CZAK_Games\AppData\Roaming\npm\node_modules\npm\npmrc Completed in 1ms
6 timing config:load:builtin Completed in 1ms
7 timing config:load:cli Completed in 1ms
8 timing config:load:env Completed in 0ms
9 timing config:load:file:D:\server\rustPlusPlus-master\rustPlusPlus\.npmrc Completed in 1ms
10 timing config:load:project Completed in 1ms
11 timing config:load:file:C:\Users\CZAK_Games\.npmrc Completed in 0ms
12 timing config:load:user Completed in 0ms
13 timing config:load:file:C:\Users\CZAK_Games\AppData\Roaming\npm\etc\npmrc Completed in 0ms
14 timing config:load:global Completed in 0ms
15 timing config:load:validate Completed in 0ms
16 timing config:load:credentials Completed in 1ms
17 timing config:load:setEnvs Completed in 0ms
18 timing config:load Completed in 7ms
19 timing npm:load:configload Completed in 7ms
20 timing npm:load:mkdirpcache Completed in 0ms
21 timing npm:load:mkdirplogs Completed in 0ms
22 verbose title npm install
23 verbose argv "install"
24 timing npm:load:setTitle Completed in 1ms
25 timing config:load:flatten Completed in 3ms
26 timing npm:load:display Completed in 4ms
27 verbose logfile logs-max:10 dir:C:\Users\CZAK_Games\AppData\Local\npm-cache\_logs
28 verbose logfile C:\Users\CZAK_Games\AppData\Local\npm-cache\_logs\2022-08-07T19_26_21_024Z-debug-0.log
29 timing npm:load:logFile Completed in 4ms
30 timing npm:load:timers Completed in 0ms
31 timing npm:load:configScope Completed in 0ms
32 timing npm:load Completed in 17ms
33 timing arborist:ctor Completed in 1ms
34 silly logfile start cleaning logs, removing 2 files
35 silly logfile done cleaning log files
36 timing idealTree:init Completed in 145ms
37 timing idealTree:userRequests Completed in 0ms
38 silly idealTree buildDeps
39 timing idealTree:#root Completed in 0ms
40 silly fetch manifest jpeg-js@0.4.2
41 http fetch GET 200 https://registry.npmjs.org/jpeg-js 996ms (cache revalidated)
42 timing idealTree Completed in 1147ms
43 timing command:install Completed in 1158ms
44 verbose stack TypeError: Invalid Version: ^0.4.3
44 verbose stack     at new SemVer (C:\Users\CZAK_Games\AppData\Roaming\npm\node_modules\npm\node_modules\semver\classes\semver.js:38:13)
44 verbose stack     at compare (C:\Users\CZAK_Games\AppData\Roaming\npm\node_modules\npm\node_modules\semver\functions\compare.js:3:32)
44 verbose stack     at Object.gte (C:\Users\CZAK_Games\AppData\Roaming\npm\node_modules\npm\node_modules\semver\functions\gte.js:2:30)
44 verbose stack     at CanPlaceDep.checkCanPlaceCurrent (C:\Users\CZAK_Games\AppData\Roaming\npm\node_modules\npm\node_modules\@npmcli\arborist\lib\can-place-dep.js:173:51)
44 verbose stack     at CanPlaceDep.checkCanPlace (C:\Users\CZAK_Games\AppData\Roaming\npm\node_modules\npm\node_modules\@npmcli\arborist\lib\can-place-dep.js:157:27)
44 verbose stack     at new CanPlaceDep (C:\Users\CZAK_Games\AppData\Roaming\npm\node_modules\npm\node_modules\@npmcli\arborist\lib\can-place-dep.js:114:26)
44 verbose stack     at PlaceDep.place (C:\Users\CZAK_Games\AppData\Roaming\npm\node_modules\npm\node_modules\@npmcli\arborist\lib\place-dep.js:123:19)
44 verbose stack     at new PlaceDep (C:\Users\CZAK_Games\AppData\Roaming\npm\node_modules\npm\node_modules\@npmcli\arborist\lib\place-dep.js:73:10)
44 verbose stack     at C:\Users\CZAK_Games\AppData\Roaming\npm\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\build-ideal-tree.js:990:31
44 verbose stack     at Array.map (<anonymous>)
45 verbose cwd D:\server\rustPlusPlus-master\rustPlusPlus
46 verbose Windows_NT 10.0.19044
47 verbose node v16.16.0
48 verbose npm  v8.16.0
49 error Invalid Version: ^0.4.3
50 verbose exit 1
51 timing npm Completed in 1277ms
52 verbose unfinished npm timer reify 1659900381143
53 verbose unfinished npm timer reify:loadTrees 1659900381150
54 verbose unfinished npm timer idealTree:buildDeps 1659900381296
55 verbose unfinished npm timer idealTree:node_modules/@jimp/jpeg 1659900381297
56 verbose code 1
57 error A complete log of this run can be found in:
57 error     C:\Users\CZAK_Games\AppData\Local\npm-cache\_logs\2022-08-07T19_26_21_024Z-debug-0.log

**Comment by alexemanuelol** [comment]
Solved in 5749daca806adc007f3d180ecd8f3b6bac7ad35e
