### ISSUE TITLE
Feature to enable teammates to register their fcm credentials

### ISSUE THREAD

**Issue by alexemanuelol** [alexemanuelol/rustPlusPlus#55]
Which in turn will make it possible to expand the usage of !leader command.

**Comment by FaiThiX** [comment]
any plans on an eta for this feature?

**Comment by alexemanuelol** [comment]
> any plans on an eta for this feature?

No ETA at the moment.

**Comment by alexemanuelol** [comment]
@FaiThiX This is currently being worked on right now.

**Comment by alexemanuelol** [comment]
Solved in v1.6.0

**Comment by bbm-design** [comment]
Hello, i'm looking at the credentials folder to check the multiple leader feature, but i see no array on the file, that could allow to add multiple users.
transforming credentials to an array could solve it

**Comment by alexemanuelol** [comment]
> 

I suggest you take a look at commits 4e1ea5b1c6c3214a9f55532d0108dc93a97f5f8f and eb1e2d6f113fb1b0b1a016d7750eb760e19e63be. And more specifically you can take a look at the credentials.js file to see how the credentials are stored.
