### ISSUE TITLE
Add ability to disable certain tracker notifications

### ISSUE THREAD

**Issue by nerif-tafu** [alexemanuelol/rustPlusPlus#60]
It would be nice to disable certain notifications from the tracker tag such as "xx just died at xx" but still leave login notifications enabled.

Perhaps adding this to #settings menu or even as a simple slash command?

**Comment by alexemanuelol** [comment]
![image](https://user-images.githubusercontent.com/18254752/186722521-45e92e72-34c3-4e39-84dd-6876e3d4dbb1.png)
You mean like this? :P

**Comment by nerif-tafu** [comment]
I'm blind 😅, thanks for the great project
