### ISSUE TITLE
Blink/Flash/Pattern for switches

### ISSUE THREAD

**Issue by JustinRR** [alexemanuelol/rustPlusPlus#64]
After going through line and line of code, I could not figure out the best way to make this happen. For example, I wanted to make a custom command for !{switchname} strobe {secs between on/off} {optional: how long to keep flashing} 

Is this possible? Or because of the discord button integration, it is limited?

**Comment by alexemanuelol** [comment]
Ofcourse it is possible, anything is possible! 😉 But doing that it would pretty fast result in rate limitation.
