### ISSUE TITLE
Getting an issue 2022-9-13 23:58:30 ERROR: {"code":"DisallowedIntents"}

### ISSUE THREAD

**Issue by andrewdens** [alexemanuelol/rustPlusPlus#74]
Tried updating the folder and then had issues so started from scratch and tried following installation steps and am now getting this issue when attempting to do npm start run.

PS C:\opt\rust\rustPlusPlus> npm start run
npm WARN config global `--global`, `--local` are deprecated. Use `--location=global` instead.
> rustPlusPlus@1.2.0 start
> ts-node . "run"

**Comment by andrewdens** [comment]
Discord changed their permissions I forgot to do the step to allow privileged intents

**Comment by bloodskin** [comment]
seems to be happening again
