### ISSUE TITLE
Cannot see Event Notification settings in settings text channel

### ISSUE THREAD

**Issue by andrewdens** [alexemanuelol/rustPlusPlus#75]
The Settings channel only displays General Settings and I can't see anything related to event notifications

**Comment by alexemanuelol** [comment]
Run `/reset discord`

**Comment by andrewdens** [comment]
I did that and got an error when running that command, the settings channel refreshed and still doesn't have event settings.

**Comment by andrewdens** [comment]
This was my error displayed when tried to run that command. 
2022-9-14 10:02:25 ERROR: Could not find message: 1019505406885769297
2022-9-14 10:02:27 RATELIMITED: Timeout: 3898, Limit: 5, Method: POST, Path: https://discord.com/api/v10/channels/1019504131666362398/messages, Route: /channels/:id/messages, Global: false
2022-9-14 10:02:33 ERROR: ReferenceError: guildId is not defined
2022-9-14 10:02:33 ERROR: There was an error while executing this command!

**Comment by alexemanuelol** [comment]
Ahh my bad, I must have messed something up, will fix it in a min
