### ISSUE TITLE
Bot resets permissions for text channels on restart

### ISSUE THREAD

**Issue by nerif-tafu** [alexemanuelol/rustPlusPlus#81]
I would like to have the ability to limit the channel category to a certain group of users. Whenever I have to restart the bot, these permissions are reset.

**Comment by alexemanuelol** [comment]
The /role command doesn't work?

**Comment by nerif-tafu** [comment]
RTFM once again.

**Comment by alexemanuelol** [comment]
To be fair, some parts of the manual isnt up to date atm, should prob look into that soon.
