### ISSUE TITLE
ERROR: {"code":"TokenInvalid"}

### ISSUE THREAD

**Issue by bronson-bohnet** [alexemanuelol/rustPlusPlus#82]
Using "docker run --rm -it -v ${pwd}/credentials:/app/credentials -v ${pwd}/instances:/app/instances -v ${pwd}/logs:/app/logs -e DISCORD_CLIENT_ID=111....1111 -e DISCORD_TOKEN=token --name rpp ghcr.io/alexemanuelol/rustPlusPlus" results in error "2022-10-08 02:00:12 ERROR: {"code":"TokenInvalid"}"

I've redone the bot multiple times and confirmed that the token is correct. Manually installing the repo, I get the same result even with the correct values placed in docker-compose.yml.

I noticed the config.json was removed, decided to add it back in for testing and it progresses through this first error.  I then get the error:
 `  errno: -4058,
  syscall: 'open',
  code: 'ENOENT',
  path: 'C:\\Users\\user\\rustPlusPlus\\src\\languages\\undefined.json'`

I've followed the instructions in docs and verified the bot token/permissions/membership.

**Comment by alexemanuelol** [comment]
If you've set the token and client id in the docket-compose file, you should run the command:
docker-compose up -d

**Comment by bronson-bohnet** [comment]
Looking at the updated documentation request, changing environment variables to RPP_DISCORD_CLIENT_ID and RPP_DISCORD_TOKEN have resolved this issue for me in both cases.
