### ISSUE TITLE
Fresh install windows 10

### ISSUE THREAD

**Issue by Owned67** [alexemanuelol/rustPlusPlus#94]
`F:\rust\Bot Rust\rustPlusPlus>npm install
npm WARN deprecated request-promise@4.2.6: request-promise has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142

> rustPlusPlus@1.6.0 preinstall
> npx npm-force-resolutions

Need to install the following packages:
  npm-force-resolutions@0.0.10
Ok to proceed? (y) y`

**Comment by alexemanuelol** [comment]
Does it hinder you from running the bot? Only looks like warnings.

**Comment by Owned67** [comment]
All good, just for report warning ^^
