### ISSUE TITLE
Suggest Always on or off Smart Switch option

### ISSUE THREAD

**Issue by YakovAU** [alexemanuelol/rustplusplus#98]
Upon server restart, smart switches can glitch out and turn off / turn on what they were originally set to.
I love the auto night / day feature but is it possible we could get an additional option that ensures its forced always on or off?
cheers, love the bot.

**Comment by alexemanuelol** [comment]
This would be possible, might add this in the future or if someone else is eager to contribute 👍

**Comment by alexemanuelol** [comment]
Added in 1fdf9671a5d6602a4f8287042ab91d5c5b749e26
Switches "life" status is checked every 5 minutes, I've set the auto-on/auto-off check during that same interval.
