### ISSUE TITLE
Cant run after fresh install

### ISSUE THREAD

**Issue by nerif-tafu** [alexemanuelol/rustPlusPlus#99]
After git cloning and running npm install no config.json file was generated. I manually created using the video install as an example, however, when I started the server with node . I was show the below error. 

I have tried this on both Windows 22H2 (22623.1020) and Linux Mint 20.3 with Node v18

```
PS D:\Documents\Gaming\Rust\rustPlusPlus> node .
node:internal/fs/utils:348
    throw err;
    ^

Error: ENOENT: no such file or directory, open 'D:\Documents\Gaming\Rust\rustPlusPlus\src\languages\undefined.json'
    at Object.openSync (node:fs:600:3)
    at Object.readFileSync (node:fs:468:35)
    at DiscordBot.loadBotIntl (D:\Documents\Gaming\Rust\rustPlusPlus\src\structures\DiscordBot.js:93:40)
    at new DiscordBot (D:\Documents\Gaming\Rust\rustPlusPlus\src\structures\DiscordBot.js:60:14)
    at Object.<anonymous> (D:\Documents\Gaming\Rust\rustPlusPlus\index.ts:29:16)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Module._load (node:internal/modules/cjs/loader:878:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12) {
  errno: -4058,
  syscall: 'open',
  code: 'ENOENT',
  path: 'D:\\Documents\\Gaming\\Rust\\rustPlusPlus\\src\\languages\\undefined.json'
}

Node.js v18.12.1

**Comment by C74K** [comment]
> After git cloning and running npm install no config.json file was generated. I manually created using the video install as an example, however, when I started the server with node . I was show the below error.
> 
> I have tried this on both Windows 22H2 (22623.1020) and Linux Mint 20.3 with Node v18
> 
> ```
> PS D:\Documents\Gaming\Rust\rustPlusPlus> node .
> node:internal/fs/utils:348
>     throw err;
>     ^
> 
> Error: ENOENT: no such file or directory, open 'D:\Documents\Gaming\Rust\rustPlusPlus\src\languages\undefined.json'
>     at Object.openSync (node:fs:600:3)
>     at Object.readFileSync (node:fs:468:35)
>     at DiscordBot.loadBotIntl (D:\Documents\Gaming\Rust\rustPlusPlus\src\structures\DiscordBot.js:93:40)
>     at new DiscordBot structures\DiscordBot.js:60:14)
>     at Object.<anonymous> (D:\Documents\Gaming\Rust\rustPlusPlus\index.ts:29:16)
>     at Module._compile (node:internal/modules/cjs/loader:1159:14)
>     at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
>     at Module.load (node:internal/modules/cjs/loader:1037:32)
>     at Module._load (node:internal/modules/cjs/loader:878:12)
>     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12) {
>   errno: -4058,
>   syscall: 'open',
>   code: 'ENOENT',
>   path: 'D:\\Documents\\Gaming\\Rust\\rustPlusPlus\\src\\languages\\undefined.json'
> }
> 
> Node.js v18.12.1
> ```
> 
> [config.zip](https://github.com/alexemanuelol/rustPlusPlus/files/10148887/config.zip)

D:\Documents\Gaming\Rust\rustPlusPlus\config\

**Comment by nerif-tafu** [comment]
I'm not sure exactly what you are trying to say; I ran the exact steps as above previously in my first comment

```
PS C:\Users\Nerif\AA> git clone https://github.com/alexemanuelol/rustPlusPlus.git
Cloning into 'rustPlusPlus'...
remote: Enumerating objects: 5749, done.
remote: Counting objects: 100% (845/845), done.
remote: Compressing objects: 100% (189/189), done.
remote: Total 5749 (delta 708), reused 742 (delta 656), pack-reused 4904
Receiving objects: 100% (5749/5749), 10.41 MiB | 8.14 MiB/s, done.
Resolving deltas: 100% (4317/4317), done.
PS C:\Users\Nerif\AA> cd rustPlusPlus
PS C:\Users\Nerif\AA\rustPlusPlus> npm install
npm WARN deprecated request-promise@4.2.6: request-promise has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142

> rustPlusPlus@1.6.0 preinstall
> npx npm-force-resolutions


added 466 packages, and audited 467 packages in 16s

32 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
PS C:\Users\Nerif\AA\rustPlusPlus> node .
2022-12-05 15:13:57 ERROR: {"code":"TokenInvalid"}
PS C:\Users\Nerif\AA\rustPlusPlus> node .
node:internal/fs/utils:348
    throw err;
    ^

Error: ENOENT: no such file or directory, open 'C:\Users\Nerif\AA\rustPlusPlus\src\languages\undefined.json'
    at Object.openSync (node:fs:600:3)
    at Object.readFileSync (node:fs:468:35)
    at DiscordBot.loadBotIntl (C:\Users\Nerif\AA\rustPlusPlus\src\structures\DiscordBot.js:93:40)
    at new DiscordBot (C:\Users\Nerif\AA\rustPlusPlus\src\structures\DiscordBot.js:60:14)
    at Object.<anonymous> (C:\Users\Nerif\AA\rustPlusPlus\index.ts:29:16)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Module._load (node:internal/modules/cjs/loader:878:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12) {
  errno: -4058,
  syscall: 'open',
  code: 'ENOENT',
  path: 'C:\\Users\\Nerif\\AA\\rustPlusPlus\\src\\languages\\undefined.json'
}

Node.js v18.12.1
PS C:\Users\Nerif\AA\rustPlusPlus>
```

**Comment by C74K** [comment]
error in config _"{"code":"TokenInvalid"}"_ use notepad++ to edit file no notepad

**Comment by C74K** [comment]
upload your index.ts from config folder

**Comment by C74K** [comment]
> @C74K I revoked my discord token as I didn't want this public; however, when I was testing, this was correct. My index.ts file is exactly the same as the most recent commit as it was simply cloned from this repository

log showing token invalid

**Comment by Richkan1** [comment]
i have the same issue as described by OP

**Comment by nerif-tafu** [comment]
@alexemanuelol Is it intended for this to be the new config file location, or is there meant to be a .env file? If so, I'll make a PR with the documentation changes.

**Comment by alexemanuelol** [comment]
@Richkan1 Correct, since the docker change you now edit the config/index.js file. I've forgotten to update the documentation instructions for it.

Try running *npm start run* instead of *node .*

**Comment by alexemanuelol** [comment]
Updated the documentation regarding the move of config file.
